namespace OdfKit.Drawing;

/// <summary>
/// Configures practical flow-diagram layout generated by the drawing builder.
/// 設定繪圖 builder 產生實務流程圖的版面。
/// </summary>
public sealed class OdfFlowLayoutOptions
{
    /// <summary>
    /// Gets or sets whether nodes flow horizontally.
    /// 取得或設定節點是否水平排列。
    /// </summary>
    public bool Horizontal { get; set; } = true;

    /// <summary>
    /// Gets or sets the start X position in centimeters.
    /// 取得或設定起始 X 位置（公分）。
    /// </summary>
    public double StartXCm { get; set; } = 1;

    /// <summary>
    /// Gets or sets the start Y position in centimeters.
    /// 取得或設定起始 Y 位置（公分）。
    /// </summary>
    public double StartYCm { get; set; } = 1.5;

    /// <summary>
    /// Gets or sets the node width in centimeters.
    /// 取得或設定節點寬度（公分）。
    /// </summary>
    public double NodeWidthCm { get; set; } = 3.2;

    /// <summary>
    /// Gets or sets the node height in centimeters.
    /// 取得或設定節點高度（公分）。
    /// </summary>
    public double NodeHeightCm { get; set; } = 1.4;

    /// <summary>
    /// Gets or sets the gap between nodes in centimeters.
    /// 取得或設定節點間距（公分）。
    /// </summary>
    public double GapCm { get; set; } = 1.2;

    /// <summary>
    /// Gets or sets the optional connector label format.
    /// 取得或設定選用的連接線標籤格式。
    /// </summary>
    /// <remarks>Use <c>{0}</c> for the source id and <c>{1}</c> for the target id. / 使用 <c>{0}</c> 表示來源 id，使用 <c>{1}</c> 表示目標 id。</remarks>
    public string? ConnectorLabelFormat { get; set; }
}
