using System;
using System.Collections.Generic;

namespace OdfKit.Compliance;

public static partial class OdfLocalizer
{
    private static readonly Dictionary<string, Dictionary<string, string>> SupplementalComplianceDictionaries = new(StringComparer.OrdinalIgnoreCase)
    {
        ["de"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Entfernen oder korrigieren Sie Elemente oder Attribute in ODF-Namensräumen, die nicht im Schema definiert sind.",
            ["ODF0003"] = "Platzieren Sie den mimetype-Eintrag als erstes Element im ZIP-Paket.",
            ["ODF0004"] = "Speichern Sie den mimetype-Eintrag unkomprimiert.",
            ["ODF0200"] = "Entfernen Sie unsichere oder nicht konforme ZIP-Eintragspfade.",
            ["ODF0201"] = "Entfernen Sie unsichere oder nicht konforme ZIP-Eintragspfade.",
            ["ODF0300"] = "Korrigieren Sie die XML-Struktur gemäß den ODF-Schemas.",
            ["ODF0400"] = "Fügen Sie das Attribut office:version in {0} hinzu oder korrigieren Sie es.",
            ["ODF0500"] = "Korrigieren Sie den office:body-Inhaltstyp, damit er zum MIME-Typ und zur Dateiendung passt.",
            ["ODF0501"] = "Korrigieren Sie den office:body-Inhaltstyp, damit er zum MIME-Typ und zur Dateiendung passt.",
            ["ODF1000"] = "Prüfen Sie, dass die Dokumentversion dem ausgewählten Konformitätsprofil entspricht.",
            ["ODF1001"] = "Prüfen Sie, dass die Dokumentversion dem ausgewählten Konformitätsprofil entspricht.",
            ["ODF1002"] = "Fügen Sie das Attribut office:version in {0} hinzu oder korrigieren Sie es.",
            ["ODF2006"] = "Korrigieren Sie den office:body-Inhaltstyp, damit er zum MIME-Typ und zur Dateiendung passt.",
            ["ODF3000"] = "Korrigieren Sie die XML-Struktur gemäß den ODF-Schemas.",
            ["ODF3002"] = "Korrigieren Sie den office:body-Inhaltstyp, damit er zum MIME-Typ und zur Dateiendung passt.",
            ["ODF3100"] = "Korrigieren Sie die XML-Struktur gemäß den ODF-Schemas.",
            ["ODF3101"] = "Korrigieren Sie die XML-Struktur gemäß den ODF-Schemas.",
            ["ODF3102"] = "Korrigieren Sie die XML-Struktur gemäß den ODF-Schemas.",
            ["PreserveCjkLayoutFeatures"] = "Stellen Sie sicher, dass vertikales CJK-Layout, Ruby, Raster und Schriftartersetzung erhalten bleiben.",
            ["RequireCrossBorderInteroperability"] = "Stellen Sie sicher, dass der zentrale Dokumentinhalt nicht von einer einzelnen herstellerspezifischen Erweiterung abhängt.",
            ["RequireGovernmentToolCompatibility"] = "Korrigieren Sie den Dokumentinhalt, um die Kompatibilität mit ODF-Anwendungswerkzeugen der Regierung der Republik China (Taiwan) sicherzustellen.",
            ["RequireIso26300Odf10Compatibility"] = "Korrigieren Sie die Dokumentstruktur, um mit der ISO/IEC 26300:2006-Basislinie (ODF 1.0) kompatibel zu bleiben.",
            ["RequireIso26300Odf13Compatibility"] = "Korrigieren Sie die Dokumentstruktur, um mit der ISO/IEC 26300:2025-Basislinie (ODF 1.3) kompatibel zu bleiben.",
            ["RequireMachineReadableMetadata"] = "Fügen Sie maschinenlesbare Metadaten wie Titel, Sprache, Daten, Autor und Dokumenttyp hinzu.",
            ["RequireOpenStandardDocumentFormat"] = "Stellen Sie sicher, dass bearbeitbare Dokumente auf öffentlich implementierbaren offenen Standards beruhen.",
            ["RequireTraditionalChineseMetadataSupport"] = "Korrigieren Sie Metadaten, Sprachkennzeichnungen und Schriftkonfigurationen für traditionelles Chinesisch."
        },
        ["fr"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Supprimez ou corrigez les éléments ou attributs des espaces de noms ODF qui ne sont pas définis dans le schéma.",
            ["ODF0003"] = "Placez l'entrée mimetype comme premier élément du paquet ZIP.",
            ["ODF0004"] = "Stockez l'entrée mimetype sans compression.",
            ["ODF0200"] = "Supprimez les chemins d'entrée ZIP dangereux ou non conformes.",
            ["ODF0201"] = "Supprimez les chemins d'entrée ZIP dangereux ou non conformes.",
            ["ODF0300"] = "Corrigez la structure XML conformément aux schémas ODF.",
            ["ODF0400"] = "Ajoutez ou corrigez l'attribut office:version dans {0}.",
            ["ODF0500"] = "Corrigez le type de contenu office:body pour qu'il corresponde au type MIME et à l'extension.",
            ["ODF0501"] = "Corrigez le type de contenu office:body pour qu'il corresponde au type MIME et à l'extension.",
            ["ODF1000"] = "Vérifiez que la version du document correspond au profil de conformité sélectionné.",
            ["ODF1001"] = "Vérifiez que la version du document correspond au profil de conformité sélectionné.",
            ["ODF1002"] = "Ajoutez ou corrigez l'attribut office:version dans {0}.",
            ["ODF2006"] = "Corrigez le type de contenu office:body pour qu'il corresponde au type MIME et à l'extension.",
            ["ODF3000"] = "Corrigez la structure XML conformément aux schémas ODF.",
            ["ODF3002"] = "Corrigez le type de contenu office:body pour qu'il corresponde au type MIME et à l'extension.",
            ["ODF3100"] = "Corrigez la structure XML conformément aux schémas ODF.",
            ["ODF3101"] = "Corrigez la structure XML conformément aux schémas ODF.",
            ["ODF3102"] = "Corrigez la structure XML conformément aux schémas ODF.",
            ["PreserveCjkLayoutFeatures"] = "Assurez la préservation de la mise en page verticale CJK, du ruby, des grilles et des substitutions de police.",
            ["RequireCrossBorderInteroperability"] = "Assurez-vous que le contenu principal du document ne dépend pas d'une extension privée d'un seul fournisseur.",
            ["RequireDeutschlandStackCompatibility"] = "Corrigez le contenu et les extensions du document pour respecter la norme de compatibilité allemande Deutschland-Stack.",
            ["RequireGovernmentToolCompatibility"] = "Corrigez le contenu du document pour garantir la compatibilité avec les outils ODF gouvernementaux de la République de Chine (Taïwan).",
            ["RequireIso26300Odf10Compatibility"] = "Corrigez la structure du document pour rester compatible avec la référence ISO/IEC 26300:2006 (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Corrigez la structure du document pour rester compatible avec la référence ISO/IEC 26300:2025 (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Ajoutez des métadonnées lisibles par machine, comme le titre, la langue, les dates, l'auteur et le type de document.",
            ["RequireOpenStandardDocumentFormat"] = "Assurez-vous que les documents modifiables restent fondés sur des standards ouverts publiquement implémentables.",
            ["RequireTraditionalChineseMetadataSupport"] = "Corrigez les métadonnées, balises de langue et configurations de police en chinois traditionnel."
        },
        ["nl"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Verwijder of corrigeer elementen of attributen in ODF-naamruimten die niet in het schema zijn gedefinieerd.",
            ["ODF0003"] = "Plaats de mimetype-vermelding als het eerste item in het ZIP-pakket.",
            ["ODF0004"] = "Sla de mimetype-vermelding zonder compressie op.",
            ["ODF0200"] = "Verwijder onveilige of niet-conforme ZIP-itempaden.",
            ["ODF0201"] = "Verwijder onveilige of niet-conforme ZIP-itempaden.",
            ["ODF0300"] = "Corrigeer de XML-structuur volgens de ODF-schema's.",
            ["ODF0400"] = "Voeg het attribuut office:version toe in {0} of corrigeer het.",
            ["ODF0500"] = "Corrigeer het office:body-inhoudstype zodat het overeenkomt met het MIME-type en de extensie.",
            ["ODF0501"] = "Corrigeer het office:body-inhoudstype zodat het overeenkomt met het MIME-type en de extensie.",
            ["ODF1000"] = "Controleer of de documentversie overeenkomt met het geselecteerde conformiteitsprofiel.",
            ["ODF1001"] = "Controleer of de documentversie overeenkomt met het geselecteerde conformiteitsprofiel.",
            ["ODF1002"] = "Voeg het attribuut office:version toe in {0} of corrigeer het.",
            ["ODF2006"] = "Corrigeer het office:body-inhoudstype zodat het overeenkomt met het MIME-type en de extensie.",
            ["ODF3000"] = "Corrigeer de XML-structuur volgens de ODF-schema's.",
            ["ODF3002"] = "Corrigeer het office:body-inhoudstype zodat het overeenkomt met het MIME-type en de extensie.",
            ["ODF3100"] = "Corrigeer de XML-structuur volgens de ODF-schema's.",
            ["ODF3101"] = "Corrigeer de XML-structuur volgens de ODF-schema's.",
            ["ODF3102"] = "Corrigeer de XML-structuur volgens de ODF-schema's.",
            ["PreserveCjkLayoutFeatures"] = "Zorg dat verticale CJK-opmaak, ruby, rasters en lettertypevervanging behouden blijven.",
            ["RequireCrossBorderInteroperability"] = "Zorg dat de kerninhoud van het document niet afhankelijk is van één leveranciersspecifieke uitbreiding.",
            ["RequireDeutschlandStackCompatibility"] = "Corrigeer documentinhoud en uitbreidingen volgens de Duitse Deutschland-Stack-compatibiliteitsnorm.",
            ["RequireForeignExtensionIsolation"] = "Plaats uitbreidingen in niet-ODF-naamruimten en zorg dat ze verwijderbaar zijn.",
            ["RequireGovernmentToolCompatibility"] = "Corrigeer documentinhoud voor compatibiliteit met ODF-toepassingstools van de regering van de Republiek China (Taiwan).",
            ["RequireIso26300Odf10Compatibility"] = "Corrigeer de documentstructuur om compatibel te blijven met de ISO/IEC 26300:2006-basislijn (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Corrigeer de documentstructuur om compatibel te blijven met de ISO/IEC 26300:2025-basislijn (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Voeg machineleesbare metadata toe, zoals titel, taal, datums, auteur en documenttype.",
            ["RequireSafeExternalResourcePolicy"] = "Gebruik ingesloten bronnen of controleer of externe verwijzingen voldoen aan het implementatiebeleid.",
            ["RequireTraditionalChineseMetadataSupport"] = "Corrigeer metadata, taaltags en lettertypeconfiguraties voor traditioneel Chinees."
        },
        ["nb"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Fjern eller korriger elementer eller attributter i ODF-navnerom som ikke er definert i skjemaet.",
            ["ODF0003"] = "Plasser mimetype-oppføringen som det første elementet i ZIP-pakken.",
            ["ODF0004"] = "Lagre mimetype-oppføringen uten komprimering.",
            ["ODF0200"] = "Fjern usikre eller ikke-konforme ZIP-oppføringsstier.",
            ["ODF0201"] = "Fjern usikre eller ikke-konforme ZIP-oppføringsstier.",
            ["ODF0300"] = "Korriger XML-strukturen i henhold til ODF-skjemaene.",
            ["ODF0400"] = "Legg til eller korriger office:version-attributtet i {0}.",
            ["ODF0500"] = "Korriger office:body-innholdstypen slik at den samsvarer med MIME-typen og filendelsen.",
            ["ODF0501"] = "Korriger office:body-innholdstypen slik at den samsvarer med MIME-typen og filendelsen.",
            ["ODF1000"] = "Kontroller at dokumentversjonen samsvarer med den valgte samsvarsprofilen.",
            ["ODF1001"] = "Kontroller at dokumentversjonen samsvarer med den valgte samsvarsprofilen.",
            ["ODF1002"] = "Legg til eller korriger office:version-attributtet i {0}.",
            ["ODF2006"] = "Korriger office:body-innholdstypen slik at den samsvarer med MIME-typen og filendelsen.",
            ["ODF3000"] = "Korriger XML-strukturen i henhold til ODF-skjemaene.",
            ["ODF3002"] = "Korriger office:body-innholdstypen slik at den samsvarer med MIME-typen og filendelsen.",
            ["ODF3100"] = "Korriger XML-strukturen i henhold til ODF-skjemaene.",
            ["ODF3101"] = "Korriger XML-strukturen i henhold til ODF-skjemaene.",
            ["ODF3102"] = "Korriger XML-strukturen i henhold til ODF-skjemaene.",
            ["PreserveCjkLayoutFeatures"] = "Sørg for at vertikal CJK-layout, ruby, rutenett og skrifterstatning bevares.",
            ["RequireCrossBorderInteroperability"] = "Sørg for at dokumentets kjerneinnhold ikke avhenger av én leverandørprivat utvidelse.",
            ["RequireDeutschlandStackCompatibility"] = "Korriger dokumentinnhold og utvidelser i samsvar med den tyske Deutschland-Stack-kompatibilitetsstandarden.",
            ["RequireForeignExtensionIsolation"] = "Plasser utvidelser i ikke-ODF-navnerom og sørg for at de kan fjernes.",
            ["RequireGovernmentToolCompatibility"] = "Korriger dokumentinnhold for kompatibilitet med ODF-verktøy fra regjeringen i Republikken Kina (Taiwan).",
            ["RequireIso26300Odf10Compatibility"] = "Korriger dokumentstrukturen for å forbli kompatibel med ISO/IEC 26300:2006-basislinjen (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Korriger dokumentstrukturen for å forbli kompatibel med ISO/IEC 26300:2025-basislinjen (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Legg til maskinlesbare metadata som tittel, språk, datoer, forfatter og dokumenttype.",
            ["RequireOpenStandardDocumentFormat"] = "Sørg for at redigerbare dokumenter fortsatt bygger på åpne standarder som kan implementeres offentlig.",
            ["RequireTraditionalChineseMetadataSupport"] = "Korriger metadata, språkkoder og skriftkonfigurasjoner for tradisjonell kinesisk."
        },
        ["pt"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Remova ou corrija elementos ou atributos em namespaces ODF que não estejam definidos no esquema.",
            ["ODF0003"] = "Coloque a entrada mimetype como o primeiro item no pacote ZIP.",
            ["ODF0004"] = "Armazene a entrada mimetype sem compressão.",
            ["ODF0200"] = "Remova caminhos de entradas ZIP inseguros ou não conformes.",
            ["ODF0201"] = "Remova caminhos de entradas ZIP inseguros ou não conformes.",
            ["ODF0300"] = "Corrija a estrutura XML de acordo com os esquemas ODF.",
            ["ODF0400"] = "Adicione ou corrija o atributo office:version em {0}.",
            ["ODF0500"] = "Corrija o tipo de conteúdo de office:body para corresponder ao tipo MIME e à extensão.",
            ["ODF0501"] = "Corrija o tipo de conteúdo de office:body para corresponder ao tipo MIME e à extensão.",
            ["ODF1000"] = "Verifique se a versão do documento corresponde ao perfil de conformidade selecionado.",
            ["ODF1001"] = "Verifique se a versão do documento corresponde ao perfil de conformidade selecionado.",
            ["ODF1002"] = "Adicione ou corrija o atributo office:version em {0}.",
            ["ODF2006"] = "Corrija o tipo de conteúdo de office:body para corresponder ao tipo MIME e à extensão.",
            ["ODF3000"] = "Corrija a estrutura XML de acordo com os esquemas ODF.",
            ["ODF3002"] = "Corrija o tipo de conteúdo de office:body para corresponder ao tipo MIME e à extensão.",
            ["ODF3100"] = "Corrija a estrutura XML de acordo com os esquemas ODF.",
            ["ODF3101"] = "Corrija a estrutura XML de acordo com os esquemas ODF.",
            ["ODF3102"] = "Corrija a estrutura XML de acordo com os esquemas ODF.",
            ["PreserveCjkLayoutFeatures"] = "Garanta a preservação de layout vertical CJK, ruby, grades e configurações de substituição de fontes.",
            ["RequireCrossBorderInteroperability"] = "Garanta que o conteúdo principal do documento não dependa de uma única extensão privada de fornecedor.",
            ["RequireDeutschlandStackCompatibility"] = "Corrija o conteúdo e as extensões do documento para cumprir o padrão alemão Deutschland-Stack.",
            ["RequireGovernmentToolCompatibility"] = "Corrija o conteúdo do documento para garantir compatibilidade com ferramentas ODF do governo da República da China (Taiwan).",
            ["RequireIso26300Odf10Compatibility"] = "Corrija a estrutura do documento para permanecer compatível com a linha de base ISO/IEC 26300:2006 (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Corrija a estrutura do documento para permanecer compatível com a linha de base ISO/IEC 26300:2025 (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Adicione metadados legíveis por máquina, como título, idioma, datas, autor e tipo de documento.",
            ["RequireOpenStandardDocumentFormat"] = "Garanta que documentos editáveis continuem baseados em padrões abertos publicamente implementáveis.",
            ["RequireSafeExternalResourcePolicy"] = "Use recursos incorporados ou garanta que referências externas cumpram a política de implantação.",
            ["RequireTraditionalChineseMetadataSupport"] = "Corrija metadados, marcas de idioma e configurações de fonte para chinês tradicional."
        },
        ["it"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Rimuovi o correggi elementi o attributi negli spazi dei nomi ODF non definiti nello schema.",
            ["ODF0003"] = "Posiziona la voce mimetype come primo elemento nel pacchetto ZIP.",
            ["ODF0004"] = "Memorizza la voce mimetype senza compressione.",
            ["ODF0200"] = "Rimuovi percorsi di voci ZIP non sicuri o non conformi.",
            ["ODF0201"] = "Rimuovi percorsi di voci ZIP non sicuri o non conformi.",
            ["ODF0300"] = "Correggi la struttura XML secondo gli schemi ODF.",
            ["ODF0400"] = "Aggiungi o correggi l'attributo office:version in {0}.",
            ["ODF0500"] = "Correggi il tipo di contenuto office:body affinché corrisponda al tipo MIME e all'estensione.",
            ["ODF0501"] = "Correggi il tipo di contenuto office:body affinché corrisponda al tipo MIME e all'estensione.",
            ["ODF1000"] = "Verifica che la versione del documento corrisponda al profilo di conformità selezionato.",
            ["ODF1001"] = "Verifica che la versione del documento corrisponda al profilo di conformità selezionato.",
            ["ODF1002"] = "Aggiungi o correggi l'attributo office:version in {0}.",
            ["ODF2006"] = "Correggi il tipo di contenuto office:body affinché corrisponda al tipo MIME e all'estensione.",
            ["ODF3000"] = "Correggi la struttura XML secondo gli schemi ODF.",
            ["ODF3002"] = "Correggi il tipo di contenuto office:body affinché corrisponda al tipo MIME e all'estensione.",
            ["ODF3100"] = "Correggi la struttura XML secondo gli schemi ODF.",
            ["ODF3101"] = "Correggi la struttura XML secondo gli schemi ODF.",
            ["ODF3102"] = "Correggi la struttura XML secondo gli schemi ODF.",
            ["PreserveCjkLayoutFeatures"] = "Assicurati che layout verticale CJK, ruby, griglie e sostituzione dei font siano preservati.",
            ["RequireCrossBorderInteroperability"] = "Assicurati che il contenuto principale del documento non dipenda da una singola estensione privata di fornitore.",
            ["RequireDeutschlandStackCompatibility"] = "Correggi contenuto ed estensioni del documento per rispettare lo standard tedesco Deutschland-Stack.",
            ["RequireForeignExtensionIsolation"] = "Inserisci le estensioni in spazi dei nomi non ODF e assicurati che siano rimovibili.",
            ["RequireGovernmentToolCompatibility"] = "Correggi il contenuto del documento per garantire compatibilità con gli strumenti ODF del governo della Repubblica di Cina (Taiwan).",
            ["RequireIso26300Odf10Compatibility"] = "Correggi la struttura del documento per restare compatibile con la baseline ISO/IEC 26300:2006 (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Correggi la struttura del documento per restare compatibile con la baseline ISO/IEC 26300:2025 (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Aggiungi metadati leggibili dalla macchina, come titolo, lingua, date, autore e tipo di documento.",
            ["RequireOpenStandardDocumentFormat"] = "Assicurati che i documenti modificabili restino basati su standard aperti pubblicamente implementabili.",
            ["RequireSafeExternalResourcePolicy"] = "Usa risorse incorporate o assicurati che i riferimenti esterni rispettino la politica di distribuzione.",
            ["RequireTraditionalChineseMetadataSupport"] = "Correggi metadati, tag lingua e configurazioni dei font per il cinese tradizionale."
        },
        ["sk"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Odstráňte alebo opravte prvky alebo atribúty v menných priestoroch ODF, ktoré nie sú definované v schéme.",
            ["ODF0003"] = "Umiestnite záznam mimetype ako prvú položku v balíku ZIP.",
            ["ODF0004"] = "Uložte záznam mimetype bez kompresie.",
            ["ODF0200"] = "Odstráňte nebezpečné alebo nevyhovujúce cesty záznamov ZIP.",
            ["ODF0201"] = "Odstráňte nebezpečné alebo nevyhovujúce cesty záznamov ZIP.",
            ["ODF0300"] = "Opravte štruktúru XML podľa schém ODF.",
            ["ODF0400"] = "Pridajte alebo opravte atribút office:version v {0}.",
            ["ODF0500"] = "Opravte typ obsahu office:body tak, aby zodpovedal typu MIME a prípone.",
            ["ODF0501"] = "Opravte typ obsahu office:body tak, aby zodpovedal typu MIME a prípone.",
            ["ODF1000"] = "Overte, že verzia dokumentu zodpovedá vybranému profilu zhody.",
            ["ODF1001"] = "Overte, že verzia dokumentu zodpovedá vybranému profilu zhody.",
            ["ODF1002"] = "Pridajte alebo opravte atribút office:version v {0}.",
            ["ODF2006"] = "Opravte typ obsahu office:body tak, aby zodpovedal typu MIME a prípone.",
            ["ODF3000"] = "Opravte štruktúru XML podľa schém ODF.",
            ["ODF3002"] = "Opravte typ obsahu office:body tak, aby zodpovedal typu MIME a prípone.",
            ["ODF3100"] = "Opravte štruktúru XML podľa schém ODF.",
            ["ODF3101"] = "Opravte štruktúru XML podľa schém ODF.",
            ["ODF3102"] = "Opravte štruktúru XML podľa schém ODF.",
            ["PreserveCjkLayoutFeatures"] = "Zabezpečte zachovanie zvislého rozloženia CJK, ruby, mriežok a náhrad písiem.",
            ["RequireCrossBorderInteroperability"] = "Zabezpečte, aby jadro obsahu dokumentu nezáviselo od jednej súkromnej rozšíriteľnosti dodávateľa.",
            ["RequireDeutschlandStackCompatibility"] = "Opravte obsah dokumentu a rozšírenia tak, aby spĺňali nemecký štandard kompatibility Deutschland-Stack.",
            ["RequireForeignExtensionIsolation"] = "Umiestnite rozšírenia do ne-ODF menných priestorov a zabezpečte, aby boli odstrániteľné.",
            ["RequireGovernmentToolCompatibility"] = "Opravte obsah dokumentu pre kompatibilitu s ODF aplikačnými nástrojmi vlády Čínskej republiky (Taiwan).",
            ["RequireIso26300Odf10Compatibility"] = "Opravte štruktúru dokumentu tak, aby zostala kompatibilná so základňou ISO/IEC 26300:2006 (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Opravte štruktúru dokumentu tak, aby zostala kompatibilná so základňou ISO/IEC 26300:2025 (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Pridajte strojovo čitateľné metadáta, ako názov, jazyk, dátumy, autora a typ dokumentu.",
            ["RequireOpenStandardDocumentFormat"] = "Zabezpečte, aby upraviteľné dokumenty zostali založené na verejne implementovateľných otvorených štandardoch.",
            ["RequireSafeExternalResourcePolicy"] = "Použite vložené zdroje alebo zabezpečte, aby externé odkazy spĺňali politiku nasadenia.",
            ["RequireTraditionalChineseMetadataSupport"] = "Opravte metadáta, jazykové značky a konfigurácie písiem pre tradičnú čínštinu."
        },
        ["da"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Fjern eller ret elementer eller attributter i ODF-navnerum, som ikke er defineret i skemaet.",
            ["ODF0003"] = "Placer mimetype-indgangen som det første element i ZIP-pakken.",
            ["ODF0004"] = "Gem mimetype-indgangen uden komprimering.",
            ["ODF0200"] = "Fjern usikre eller ikke-konforme ZIP-indgangsstier.",
            ["ODF0201"] = "Fjern usikre eller ikke-konforme ZIP-indgangsstier.",
            ["ODF0300"] = "Ret XML-strukturen i henhold til ODF-skemaerne.",
            ["ODF0400"] = "Tilføj eller ret attributten office:version i {0}.",
            ["ODF0500"] = "Ret office:body-indholdstypen, så den svarer til MIME-typen og filendelsen.",
            ["ODF0501"] = "Ret office:body-indholdstypen, så den svarer til MIME-typen og filendelsen.",
            ["ODF1000"] = "Kontrollér, at dokumentversionen svarer til den valgte overensstemmelsesprofil.",
            ["ODF1001"] = "Kontrollér, at dokumentversionen svarer til den valgte overensstemmelsesprofil.",
            ["ODF1002"] = "Tilføj eller ret attributten office:version i {0}.",
            ["ODF2006"] = "Ret office:body-indholdstypen, så den svarer til MIME-typen og filendelsen.",
            ["ODF3000"] = "Ret XML-strukturen i henhold til ODF-skemaerne.",
            ["ODF3002"] = "Ret office:body-indholdstypen, så den svarer til MIME-typen og filendelsen.",
            ["ODF3100"] = "Ret XML-strukturen i henhold til ODF-skemaerne.",
            ["ODF3101"] = "Ret XML-strukturen i henhold til ODF-skemaerne.",
            ["ODF3102"] = "Ret XML-strukturen i henhold til ODF-skemaerne.",
            ["PreserveCjkLayoutFeatures"] = "Sørg for, at lodret CJK-layout, ruby, gitter og skrifterstatning bevares.",
            ["RequireCrossBorderInteroperability"] = "Sørg for, at dokumentets kerneindhold ikke afhænger af en enkelt leverandørs private udvidelse.",
            ["RequireDeutschlandStackCompatibility"] = "Ret dokumentindhold og udvidelser, så de overholder den tyske Deutschland-Stack-kompatibilitetsstandard.",
            ["RequireForeignExtensionIsolation"] = "Placer udvidelser i ikke-ODF-navnerum, og sørg for, at de kan fjernes.",
            ["RequireGovernmentToolCompatibility"] = "Ret dokumentindhold for kompatibilitet med ODF-programværktøjer fra Republikken Kinas regering (Taiwan).",
            ["RequireIso26300Odf10Compatibility"] = "Ret dokumentstrukturen, så den forbliver kompatibel med ISO/IEC 26300:2006-baseline (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Ret dokumentstrukturen, så den forbliver kompatibel med ISO/IEC 26300:2025-baseline (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Tilføj maskinlæsbare metadata som titel, sprog, datoer, forfatter og dokumenttype.",
            ["RequireOpenStandardDocumentFormat"] = "Sørg for, at redigerbare dokumenter fortsat er baseret på offentligt implementerbare åbne standarder.",
            ["RequireSafeExternalResourcePolicy"] = "Brug indlejrede ressourcer, eller sørg for, at eksterne referencer overholder udrulningspolitikken.",
            ["RequireTraditionalChineseMetadataSupport"] = "Ret metadata, sprogmærker og skrifttypekonfigurationer for traditionelt kinesisk."
        },
        ["ms"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "Buang atau betulkan unsur atau atribut dalam ruang nama ODF yang tidak ditakrifkan dalam skema.",
            ["ODF0003"] = "Letakkan entri mimetype sebagai item pertama dalam pakej ZIP.",
            ["ODF0004"] = "Simpan entri mimetype tanpa pemampatan.",
            ["ODF0200"] = "Buang laluan entri ZIP yang tidak selamat atau tidak patuh.",
            ["ODF0201"] = "Buang laluan entri ZIP yang tidak selamat atau tidak patuh.",
            ["ODF0300"] = "Betulkan struktur XML mengikut skema ODF.",
            ["ODF0400"] = "Tambah atau betulkan atribut office:version dalam {0}.",
            ["ODF0500"] = "Betulkan jenis kandungan office:body supaya sepadan dengan jenis MIME dan sambungan fail.",
            ["ODF0501"] = "Betulkan jenis kandungan office:body supaya sepadan dengan jenis MIME dan sambungan fail.",
            ["ODF1000"] = "Sahkan bahawa versi dokumen sepadan dengan profil pematuhan yang dipilih.",
            ["ODF1001"] = "Sahkan bahawa versi dokumen sepadan dengan profil pematuhan yang dipilih.",
            ["ODF1002"] = "Tambah atau betulkan atribut office:version dalam {0}.",
            ["ODF2006"] = "Betulkan jenis kandungan office:body supaya sepadan dengan jenis MIME dan sambungan fail.",
            ["ODF3000"] = "Betulkan struktur XML mengikut skema ODF.",
            ["ODF3002"] = "Betulkan jenis kandungan office:body supaya sepadan dengan jenis MIME dan sambungan fail.",
            ["ODF3100"] = "Betulkan struktur XML mengikut skema ODF.",
            ["ODF3101"] = "Betulkan struktur XML mengikut skema ODF.",
            ["ODF3102"] = "Betulkan struktur XML mengikut skema ODF.",
            ["PreserveCjkLayoutFeatures"] = "Pastikan tata letak menegak CJK, ruby, grid dan tetapan penggantian fon dikekalkan.",
            ["RequireCrossBorderInteroperability"] = "Pastikan kandungan teras dokumen tidak bergantung pada satu sambungan peribadi vendor.",
            ["RequireDeutschlandStackCompatibility"] = "Betulkan kandungan dan sambungan dokumen supaya mematuhi standard keserasian Deutschland-Stack Jerman.",
            ["RequireForeignExtensionIsolation"] = "Letakkan sambungan dalam ruang nama bukan ODF dan pastikan sambungan boleh dibuang.",
            ["RequireGovernmentToolCompatibility"] = "Betulkan kandungan dokumen untuk memastikan keserasian dengan alat aplikasi ODF kerajaan Republik China (Taiwan).",
            ["RequireIso26300Odf10Compatibility"] = "Betulkan struktur dokumen supaya kekal serasi dengan garis dasar ISO/IEC 26300:2006 (ODF 1.0).",
            ["RequireIso26300Odf13Compatibility"] = "Betulkan struktur dokumen supaya kekal serasi dengan garis dasar ISO/IEC 26300:2025 (ODF 1.3).",
            ["RequireMachineReadableMetadata"] = "Tambah metadata boleh dibaca mesin seperti tajuk, bahasa, tarikh, pengarang dan jenis dokumen.",
            ["RequireOpenStandardDocumentFormat"] = "Pastikan dokumen boleh sunting kekal berdasarkan standard terbuka yang boleh dilaksanakan secara umum.",
            ["RequireSafeExternalResourcePolicy"] = "Gunakan sumber terbenam atau pastikan rujukan luaran mematuhi dasar pelaksanaan.",
            ["RequireTraditionalChineseMetadataSupport"] = "Betulkan metadata, tag bahasa dan konfigurasi fon untuk bahasa Cina tradisional."
        },
        ["ko"] = new(StringComparer.Ordinal)
        {
            ["DisallowInvalidOdfNamespaceExtensions"] = "스키마에 정의되지 않은 ODF 네임스페이스의 요소 또는 특성을 제거하거나 수정하십시오.",
            ["ODF0003"] = "mimetype 엔트리를 ZIP 패키지의 첫 번째 항목으로 배치하십시오.",
            ["ODF0004"] = "mimetype 엔트리를 압축하지 않고 저장하십시오.",
            ["ODF0200"] = "안전하지 않거나 준수하지 않는 ZIP 엔트리 경로를 제거하십시오.",
            ["ODF0201"] = "안전하지 않거나 준수하지 않는 ZIP 엔트리 경로를 제거하십시오.",
            ["ODF0300"] = "ODF 스키마에 따라 XML 구조를 수정하십시오.",
            ["ODF0400"] = "{0}에 office:version 특성을 추가하거나 수정하십시오.",
            ["ODF0500"] = "office:body 콘텐츠 형식이 MIME 형식 및 확장자와 일치하도록 수정하십시오.",
            ["ODF0501"] = "office:body 콘텐츠 형식이 MIME 형식 및 확장자와 일치하도록 수정하십시오.",
            ["ODF1000"] = "문서 버전이 선택한 준수 프로필과 일치하는지 확인하십시오.",
            ["ODF1001"] = "문서 버전이 선택한 준수 프로필과 일치하는지 확인하십시오.",
            ["ODF1002"] = "{0}에 office:version 특성을 추가하거나 수정하십시오.",
            ["ODF2006"] = "office:body 콘텐츠 형식이 MIME 형식 및 확장자와 일치하도록 수정하십시오.",
            ["ODF3000"] = "ODF 스키마에 따라 XML 구조를 수정하십시오.",
            ["ODF3002"] = "office:body 콘텐츠 형식이 MIME 형식 및 확장자와 일치하도록 수정하십시오.",
            ["ODF3100"] = "ODF 스키마에 따라 XML 구조를 수정하십시오.",
            ["ODF3101"] = "ODF 스키마에 따라 XML 구조를 수정하십시오.",
            ["ODF3102"] = "ODF 스키마에 따라 XML 구조를 수정하십시오.",
            ["PreserveCjkLayoutFeatures"] = "CJK 세로 레이아웃, 루비, 그리드 및 글꼴 대체 설정이 보존되도록 하십시오.",
            ["RequireCrossBorderInteroperability"] = "문서 핵심 콘텐츠가 단일 공급업체의 사설 확장에 의존하지 않도록 하십시오.",
            ["RequireDeutschlandStackCompatibility"] = "독일 Deutschland-Stack 호환성 표준을 준수하도록 문서 내용과 확장을 수정하십시오.",
            ["RequireForeignExtensionIsolation"] = "확장을 비 ODF 네임스페이스에 배치하고 제거 가능하도록 하십시오.",
            ["RequireGovernmentToolCompatibility"] = "중화민국(대만) 정부 ODF 응용 도구와 호환되도록 문서 내용을 수정하십시오.",
            ["RequireIso26300Odf10Compatibility"] = "ISO/IEC 26300:2006(ODF 1.0) 기준과 호환되도록 문서 구조를 수정하십시오.",
            ["RequireIso26300Odf13Compatibility"] = "ISO/IEC 26300:2025(ODF 1.3) 기준과 호환되도록 문서 구조를 수정하십시오.",
            ["RequireMachineReadableMetadata"] = "제목, 언어, 날짜, 작성자 및 문서 유형과 같은 기계 판독 가능 메타데이터를 추가하십시오.",
            ["RequireOpenStandardDocumentFormat"] = "편집 가능한 문서가 공개적으로 구현 가능한 개방형 표준을 기반으로 유지되도록 하십시오.",
            ["RequireSafeExternalResourcePolicy"] = "내장 리소스를 사용하거나 외부 참조가 배포 정책을 준수하는지 확인하십시오.",
            ["RequireTraditionalChineseMetadataSupport"] = "번체 중국어 메타데이터, 언어 태그 및 글꼴 구성을 수정하십시오."
        }
    };

    private static void MergeSupplementalComplianceDictionary(string name, Dictionary<string, string> target)
    {
        if (!SupplementalComplianceDictionaries.TryGetValue(name, out Dictionary<string, string>? translations))
        {
            return;
        }

        foreach (var kvp in translations)
        {
            if (!target.ContainsKey(kvp.Key))
            {
                target.Add(kvp.Key, kvp.Value);
            }
        }
    }
}
