namespace OdfKit.WebFonts;

/// <summary>
/// Describes one immutable, content-addressed WebFont asset.
/// 描述單一不可變且以內容定址的 WebFont 資產。
/// </summary>
public sealed class WebFontAsset
{
    /// <summary>
    /// Gets or initializes the server-owned asset file name without directory components.
    /// 取得或初始化不含目錄部分、由伺服器管理的資產檔名。
    /// </summary>
    public string FileName { get; init; } = string.Empty;

    /// <summary>
    /// Gets or initializes the lowercase SHA-256 digest of the asset bytes.
    /// 取得或初始化資產位元組的小寫 SHA-256 摘要。
    /// </summary>
    public string Sha256 { get; init; } = string.Empty;

    /// <summary>
    /// Gets or initializes the exact asset length in bytes.
    /// 取得或初始化資產的確切位元組長度。
    /// </summary>
    public long ByteLength { get; init; }

    /// <summary>
    /// Gets or initializes the standalone output format.
    /// 取得或初始化獨立輸出格式。
    /// </summary>
    public WebFontFormat Format { get; init; }

    /// <summary>
    /// Gets or initializes the CSS font family generated by the trusted build process.
    /// 取得或初始化由受信任建置流程產生的 CSS 字型家族。
    /// </summary>
    public string FontFamily { get; init; } = string.Empty;

    /// <summary>
    /// Gets or initializes the canonical CSS unicode-range descriptors for the asset.
    /// 取得或初始化資產的標準 CSS unicode-range 描述項目。
    /// </summary>
    public IReadOnlyList<string> UnicodeRanges { get; init; } = Array.Empty<string>();
}
