#!/usr/bin/env python3
"""Expand public/protected C# methods that use optional parameters into explicit overload chains.

Only trailing optional parameters are supported (C# language rule). Generated code under
Generated folders and // <auto-generated files are skipped.

CancellationToken-only optional parameters (``CancellationToken x = default``) are
intentionally left alone — see docs/public-api-optional-parameters.md.

Usage:
  python eng/Expand-OptionalParameters.py [--dry-run] [--path OdfKit]
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

SKIP_DIR_PARTS = {"Generated", "bin", "obj"}

METHOD_HEADER_RE = re.compile(
    r"(?P<indent>[ \t]*)"
    r"(?P<header>"
    r"(?:public|protected)\s+"
    r"(?:(?:new|static|virtual|override|async|sealed|partial|unsafe|extern|abstract)\s+)*"
    r"(?:[\w.<>\[\]?, \n\r]+?\s+)?"
    r"(?P<name>~?[\w]+)(?P<type_params>\s*<[^>{}()]+>)?\s*"
    r"\((?P<params>(?:[^()\"']|\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])*'|\([^()]*\))*)\)\s*"
    r"(?:where\s+\w+\s*:\s*[^\{=]+?\s*)*"
    r"(?::\s*(?:base|this)\s*\((?:[^()\"']|\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])*'|\([^()]*\))*\)\s*)?"
    r")"
    r"(?P<body_start>\{|=>)",
    re.MULTILINE,
)


@dataclass
class Param:
    raw: str
    name: str
    default: str | None

    @property
    def without_default(self) -> str:
        if self.default is None:
            return self.raw.strip()
        # type/modifiers + name (drop default)
        left = self.raw.split("=", 1)[0].strip()
        return left


def split_params(param_text: str) -> list[str]:
    text = param_text.strip()
    if not text:
        return []
    parts: list[str] = []
    depth = angle = bracket = 0
    in_str: str | None = None
    escape = False
    start = 0
    i = 0
    while i < len(text):
        ch = text[i]
        if in_str:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == in_str:
                in_str = None
            i += 1
            continue
        if ch in ('"', "'"):
            in_str = ch
            i += 1
            continue
        if ch == "<":
            angle += 1
        elif ch == ">":
            angle = max(0, angle - 1)
        elif ch == "[":
            bracket += 1
        elif ch == "]":
            bracket = max(0, bracket - 1)
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth - 1)
        elif ch == "," and depth == 0 and angle == 0 and bracket == 0:
            parts.append(text[start:i].strip())
            start = i + 1
        i += 1
    tail = text[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def parse_params(param_text: str) -> list[Param] | None:
    parts = split_params(param_text)
    params: list[Param] = []
    seen_default = False
    for part in parts:
        cleaned = re.sub(r"^\s*(?:\[[^\]]*\]\s*)+", "", part).strip()
        if not cleaned:
            continue
        # ref/out/in parameters cannot be expanded via simple forwarding
        if re.search(r"\b(ref|out|in)\b", cleaned):
            return None
        # top-level '='
        depth = angle = bracket = 0
        in_str: str | None = None
        escape = False
        eq = -1
        for i, ch in enumerate(cleaned):
            if in_str:
                if escape:
                    escape = False
                elif ch == "\\":
                    escape = True
                elif ch == in_str:
                    in_str = None
                continue
            if ch in ('"', "'"):
                in_str = ch
                continue
            if ch == "<":
                angle += 1
            elif ch == ">":
                angle = max(0, angle - 1)
            elif ch == "[":
                bracket += 1
            elif ch == "]":
                bracket = max(0, bracket - 1)
            elif ch == "(":
                depth += 1
            elif ch == ")":
                depth = max(0, depth - 1)
            elif ch == "=" and depth == 0 and angle == 0 and bracket == 0:
                eq = i
                break
        if eq >= 0:
            left = cleaned[:eq].strip()
            default = cleaned[eq + 1 :].strip()
            name = left.split()[-1]
            params.append(Param(raw=cleaned, name=name, default=default))
            seen_default = True
        else:
            if seen_default:
                return None
            name = cleaned.split()[-1]
            params.append(Param(raw=cleaned, name=name, default=None))
    return params


def is_cancellation_token_param(param: Param) -> bool:
    """True when the parameter type is CancellationToken (optional or required)."""
    return bool(
        re.search(
            r"(?:^|[\s,])(?:global::)?(?:System\.Threading\.)?CancellationToken\s+\w+\s*$",
            param.raw.split("=")[0].strip(),
        )
    )


def is_skip_method(name: str, header: str) -> bool:
    h = f" {header} "
    if " abstract " in h or " extern " in h:
        return True
    # Primary constructors / type declarations — never expand.
    if re.search(r"\b(class|record|struct|interface|enum)\b", header):
        return True
    return False


def strip_override_from_short(header_oneline: str) -> str:
    """Short forwarders must not use override for base virtuals with defaults."""
    return re.sub(r"\boverride\s+", "", header_oneline)


def strip_async_from_short(header_oneline: str) -> str:
    """Short forwarders that call the long form should not be async (avoid CS4014)."""
    return re.sub(r"\basync\s+", "", header_oneline)


def is_constructor_header(header: str, name: str) -> bool:
    """True when header declares an instance constructor (no return type before name)."""
    # Strip known modifiers; if next token is the type name then '('.
    h = header.strip()
    h = re.sub(
        r"^(?:public|protected|private|internal)\s+",
        "",
        h,
    )
    h = re.sub(
        r"^(?:(?:new|static|virtual|override|async|sealed|partial|unsafe|extern|abstract)\s+)+",
        "",
        h,
    )
    return bool(re.match(rf"{re.escape(name)}\s*\(", h))


def find_matching_brace(text: str, open_idx: int) -> int:
    depth = 0
    in_str: str | None = None
    in_line_comment = False
    in_block_comment = False
    escape = False
    verbat = False
    i = open_idx
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""
        if in_line_comment:
            if ch == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            if ch == "*" and nxt == "/":
                in_block_comment = False
                i += 2
                continue
            i += 1
            continue
        if in_str:
            if verbat:
                if ch == '"' and nxt == '"':
                    i += 2
                    continue
                if ch == '"':
                    in_str = None
                    verbat = False
                i += 1
                continue
            if escape:
                escape = False
                i += 1
                continue
            if ch == "\\":
                escape = True
                i += 1
                continue
            if ch == in_str:
                in_str = None
            i += 1
            continue
        if ch == "/" and nxt == "/":
            in_line_comment = True
            i += 2
            continue
        if ch == "/" and nxt == "*":
            in_block_comment = True
            i += 2
            continue
        if ch == "@" and nxt == '"':
            in_str = '"'
            verbat = True
            i += 2
            continue
        if ch in ('"', "'"):
            in_str = ch
            verbat = False
            i += 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


def find_expression_body_end(text: str, arrow_idx: int) -> int:
    if text[arrow_idx : arrow_idx + 2] != "=>":
        return -1
    i = arrow_idx + 2
    depth = 0
    in_str: str | None = None
    escape = False
    in_line_comment = False
    in_block_comment = False
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""
        if in_line_comment:
            if ch == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            if ch == "*" and nxt == "/":
                in_block_comment = False
                i += 2
                continue
            i += 1
            continue
        if in_str:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == in_str:
                in_str = None
            i += 1
            continue
        if ch == "/" and nxt == "/":
            in_line_comment = True
            i += 2
            continue
        if ch == "/" and nxt == "*":
            in_block_comment = True
            i += 2
            continue
        if ch in ('"', "'"):
            in_str = ch
            i += 1
            continue
        if ch in "({[":
            depth += 1
        elif ch in ")}]":
            depth = max(0, depth - 1)
        elif ch == ";" and depth == 0:
            return i + 1
        i += 1
    return -1


def extract_xml_doc(text: str, header_start: int) -> tuple[str, int]:
    line_start = text.rfind("\n", 0, header_start) + 1
    pos = line_start
    docs_start = pos
    cursor = pos
    while cursor > 0:
        prev_nl = text.rfind("\n", 0, cursor - 1)
        line = text[prev_nl + 1 : cursor]
        stripped = line.strip()
        if stripped.startswith("///"):
            docs_start = prev_nl + 1
            cursor = prev_nl + 1 if prev_nl >= 0 else 0
            if prev_nl < 0:
                break
            continue
        if stripped == "" and docs_start != pos:
            docs_start = prev_nl + 1
            cursor = prev_nl + 1 if prev_nl >= 0 else 0
            continue
        break
    chunk = text[docs_start:pos]
    if chunk.strip().startswith("///"):
        return chunk, docs_start
    return "", header_start


def build_forward_args(params: list[Param], count: int) -> str:
    args: list[str] = []
    for i, p in enumerate(params):
        if i < count:
            args.append(p.name)
        else:
            assert p.default is not None
            args.append(p.default)
    return ", ".join(args)


def rebuild_expansion(
    indent: str,
    header: str,
    name: str,
    params_text: str,
    body_token: str,
    body_after_token: str,
    xml_doc: str,
    attributes: str,
) -> str | None:
    params = parse_params(params_text)
    if params is None or not any(p.default is not None for p in params):
        return None
    if is_skip_method(name, header):
        return None

    required = [p for p in params if p.default is None]
    optional = [p for p in params if p.default is not None]
    # Public CancellationToken = default is an allowed .NET SDK shape
    # (docs/public-api-optional-parameters.md). Do not expand CT-only optionals.
    if optional and all(is_cancellation_token_param(p) for p in optional):
        return None
    # Expand any number of trailing optionals into explicit overload chains.
    # Call sites that used named middle-skipping must pass explicit nulls / defaults
    # (0.x has no published API compatibility requirement).
    if len(optional) < 1:
        return None
    m = re.search(
        rf"\b{re.escape(name)}(?P<type_params>\s*<[^>{{}}()]+>)?\s*\(",
        header,
    )
    if not m:
        return None
    type_params = m.group("type_params") or ""
    start_paren = header.find("(", m.start())
    depth = 0
    end_paren = -1
    for index in range(start_paren, len(header)):
        if header[index] == "(":
            depth += 1
        elif header[index] == ")":
            depth -= 1
            if depth == 0:
                end_paren = index
                break
    if end_paren < 0:
        return None
    pre = header[: m.start()]
    post = header[end_paren + 1 :]
    full_params = ", ".join(p.without_default for p in params)
    full_header = f"{pre}{name}{type_params}({full_params}){post}".rstrip()
    is_ctor = is_constructor_header(header, name)
    # Constructors with : base(...) / : this(...) already — only expand if post is empty or we keep post on full only
    if is_ctor and re.search(r":\s*(base|this)\s*\(", post):
        # Chained constructors: short overloads use this(...); full keeps original chain
        pass

    # Collapse multi-line header pre/post whitespace for short overloads
    def oneline(s: str) -> str:
        return re.sub(r"\s+", " ", s).strip()

    parts: list[str] = []
    for n_opt in range(0, len(optional)):
        take = required + optional[:n_opt]
        plist = ", ".join(p.without_default for p in take)
        # short ctors never re-attach : base/this from the long form
        short_post = "" if is_ctor else post
        short_header = oneline(f"{pre}{name}{type_params}({plist}){short_post}")
        # override on short overload is invalid when base only declares the long form
        short_header = strip_override_from_short(short_header)
        short_header = strip_async_from_short(short_header)
        forward = build_forward_args(params, len(take))
        if is_ctor:
            # expression-bodied ctor must use this(...)
            if body_token != "{":
                # rare for ctor; skip expansion
                return None
            parts.append(
                f"{indent}/// <summary>\n"
                f"{indent}/// Convenience overload that uses default values for remaining parameters.\n"
                f"{indent}/// 便利多載：其餘參數使用預設值並轉呼叫最長多載。\n"
                f"{indent}/// </summary>\n"
                f"{indent}{short_header} : this({forward}) {{ }}\n"
                f"\n"
            )
        else:
            parts.append(
                f"{indent}/// <summary>\n"
                f"{indent}/// Convenience overload that uses default values for remaining parameters.\n"
                f"{indent}/// 便利多載：其餘參數使用預設值並轉呼叫最長多載。\n"
                f"{indent}/// </summary>\n"
                f"{indent}{short_header} => {name}{type_params}({forward});\n"
                f"\n"
            )

    if xml_doc:
        parts.append(xml_doc if xml_doc.endswith("\n") else xml_doc + "\n")
    if attributes.strip().startswith("["):
        parts.append(attributes if attributes.endswith("\n") else attributes + "\n")

    fh = oneline(full_header) if "\n" not in full_header.strip() else full_header.strip()
    # Prefer keeping multi-line full header if original was multi-line
    if "\n" in header.strip():
        # rebuild multi-line full header simply as single line for stability
        fh = oneline(full_header)

    if body_token == "{":
        # body_after_token is content starting after `{` through closing `}`
        parts.append(f"{indent}{fh}\n{indent}{{{body_after_token}")
        if not parts[-1].endswith("\n"):
            parts.append("\n")
    else:
        bt = body_after_token
        if not bt.strip().endswith(";"):
            bt = bt.rstrip() + ";"
        # ensure leading space after =>
        if not bt.startswith(" ") and not bt.startswith("\n"):
            bt = " " + bt
        parts.append(f"{indent}{fh} =>{bt}")
        if not parts[-1].endswith("\n"):
            parts.append("\n")

    return "".join(parts)


def process_file(path: Path, dry_run: bool) -> int:
    text = path.read_text(encoding="utf-8")
    if any(part in SKIP_DIR_PARTS for part in path.parts):
        return 0
    if text.lstrip().startswith("// <auto-generated"):
        return 0

    expansions = 0
    out: list[str] = []
    pos = 0

    for m in METHOD_HEADER_RE.finditer(text):
        if m.start() < pos:
            continue

        name = m.group("name")
        params_text = m.group("params")
        if "=" not in params_text:
            continue
        if not re.search(r"=\s*(?:null|default|true|false|[\w.\"]+|\d)", params_text):
            continue

        indent = m.group("indent")
        header = m.group("header")
        if is_skip_method(m.group("name"), header):
            continue
        # Skip if the match is a primary constructor (type keyword just before name)
        pre_context = text[max(0, m.start() - 120) : m.start()]
        if re.search(r"\b(class|record|struct|interface)\s+$", pre_context.replace("\n", " ")):
            continue
        # Types with a primary constructor parameter list cannot declare
        # additional constructors without this(...) chaining carefully; skip
        # instance ctors in those types entirely.
        if is_constructor_header(header, m.group("name")):
            # Detect `class Foo(...)` primary ctor earlier in file
            type_name = m.group("name")
            if re.search(
                rf"\b(?:class|record|struct)\s+{re.escape(type_name)}\s*\(",
                text[: m.start()],
            ):
                continue
        body_token = m.group("body_start")
        body_abs = m.start("body_start")

        if body_token == "{":
            end = find_matching_brace(text, body_abs)
            if end < 0:
                continue
            body_after = text[body_abs + 1 : end + 1]
            full_end = end + 1
        else:
            end = find_expression_body_end(text, body_abs)
            if end < 0:
                continue
            body_after = text[body_abs + 2 : end]
            full_end = end

        xml_doc, doc_start = extract_xml_doc(text, m.start())
        replace_start = doc_start if xml_doc else m.start()
        between = text[doc_start + len(xml_doc) : m.start()] if xml_doc else ""
        # attributes only
        attributes = between if between.strip().startswith("[") else ""
        if between and not attributes and between.strip():
            # keep non-attribute between (should be rare)
            attributes = between

        rebuilt = rebuild_expansion(
            indent=indent,
            header=header,
            name=name,
            params_text=params_text,
            body_token=body_token,
            body_after_token=body_after,
            xml_doc=xml_doc,
            attributes=attributes,
        )
        if not rebuilt:
            continue

        out.append(text[pos:replace_start])
        out.append(rebuilt)
        pos = full_end
        expansions += 1

    if expansions == 0:
        return 0

    out.append(text[pos:])
    new_text = "".join(out)
    if not dry_run:
        # preserve original newline style if mostly CRLF
        if "\r\n" in text:
            new_text = new_text.replace("\r\n", "\n").replace("\n", "\r\n")
        path.write_text(new_text, encoding="utf-8")
    return expansions


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--path", default="OdfKit")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    root = Path(args.path)
    total_exp = 0
    total_files = 0
    for path in sorted(root.rglob("*.cs")):
        if any(part in SKIP_DIR_PARTS for part in path.parts):
            continue
        exp = process_file(path, dry_run=args.dry_run)
        if exp:
            total_exp += exp
            total_files += 1
            print(f"{path}: {exp} methods expanded")
    print(f"Total: {total_exp} methods in {total_files} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
