#Requires -Version 7.0
<#
.SYNOPSIS
    自 JSON 語系來源產生 OdfLocalizer.Exceptions.<culture>.cs。
.DESCRIPTION
    v0.0.1 在地化產線：`OdfKit/Compliance/i18n/exceptions.<culture>.json` 為訊息
    字串的單一來源真相；本腳本產生對應 C# 字典 partial，供執行期載入。

    產生後會驗證 12 語系鍵集合與 en 對等。

.PARAMETER VerifyOnly
    只檢查既有 .cs 是否與 JSON 一致（不寫檔）；不一致時以非零結束。
#>
[CmdletBinding()]
param(
    [switch]$VerifyOnly
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$i18nDir = Join-Path $repoRoot 'OdfKit/Compliance/i18n'
$complianceDir = Join-Path $repoRoot 'OdfKit/Compliance'
$cultures = @('en', 'zh-TW', 'de', 'fr', 'nl', 'nb', 'pt', 'it', 'sk', 'da', 'ms', 'ko')

function Get-MethodName {
    param([string]$Culture)
    switch ($Culture) {
        'zh-TW' { return 'AddExceptionDictionaryZhTw' }
        default {
            $parts = $Culture -split '-'
            $suffix = ($parts | ForEach-Object { $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1).ToLowerInvariant() }) -join ''
            return "AddExceptionDictionary$suffix"
        }
    }
}

function Escape-CsString {
    param([string]$Value)
    if ($null -eq $Value) { return '' }
    return $Value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
}

function Read-ExceptionJson {
    param([string]$Path)
    $raw = [System.IO.File]::ReadAllText($Path)
    $obj = $raw | ConvertFrom-Json
    $map = [ordered]@{}
    foreach ($prop in $obj.PSObject.Properties) {
        $map[$prop.Name] = [string]$prop.Value
    }
    return $map
}

function Build-ExceptionCs {
    param(
        [string]$Culture,
        [System.Collections.Specialized.OrderedDictionary]$Map
    )
    $method = Get-MethodName -Culture $Culture
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('// <auto-generated />')
    [void]$sb.AppendLine('// 由此檔案產生：eng/Generate-LocalizerExceptionsFromJson.ps1')
    [void]$sb.AppendLine("// 來源：OdfKit/Compliance/i18n/exceptions.$Culture.json")
    [void]$sb.AppendLine('// 請勿手改本檔；請編輯 JSON 後重跑產生腳本。')
    [void]$sb.AppendLine('using System;')
    [void]$sb.AppendLine('using System.Collections.Generic;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('namespace OdfKit.Compliance;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('public static partial class OdfLocalizer')
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    private static void $method(Dictionary<string, Dictionary<string, string>> map)")
    [void]$sb.AppendLine('    {')
    [void]$sb.AppendLine("        map[`"$Culture`"] = new(StringComparer.Ordinal)")
    [void]$sb.AppendLine('        {')
    foreach ($key in $Map.Keys) {
        $val = Escape-CsString -Value ([string]$Map[$key])
        [void]$sb.AppendLine("            [`"$key`"] = `"$val`",")
    }
    [void]$sb.AppendLine('        };')
    [void]$sb.AppendLine('    }')
    [void]$sb.AppendLine('}')
    return $sb.ToString()
}

$utf8Bom = New-Object System.Text.UTF8Encoding $true
$baseline = $null
$mismatch = 0

foreach ($culture in $cultures) {
    $jsonPath = Join-Path $i18nDir "exceptions.$culture.json"
    if (-not (Test-Path -LiteralPath $jsonPath)) {
        throw "缺少 JSON 來源：$jsonPath"
    }

    $map = Read-ExceptionJson -Path $jsonPath
    if ($map.Count -eq 0) {
        throw "JSON 無訊息鍵：$jsonPath"
    }

    if ($null -eq $baseline) {
        $baseline = [System.Collections.Generic.HashSet[string]]::new([string[]]@($map.Keys), [StringComparer]::Ordinal)
    }
    else {
        $current = [System.Collections.Generic.HashSet[string]]::new([string[]]@($map.Keys), [StringComparer]::Ordinal)
        foreach ($k in $baseline) {
            if (-not $current.Contains($k)) {
                Write-Host "FAIL [$culture] 缺少鍵：$k"
                $mismatch++
            }
        }
        foreach ($k in $current) {
            if (-not $baseline.Contains($k)) {
                Write-Host "FAIL [$culture] 多餘鍵：$k"
                $mismatch++
            }
        }
    }

    $csPath = Join-Path $complianceDir "OdfLocalizer.Exceptions.$culture.cs"
    $generated = Build-ExceptionCs -Culture $culture -Map $map

    if ($VerifyOnly) {
        if (-not (Test-Path -LiteralPath $csPath)) {
            Write-Host "FAIL 缺少產生檔：$csPath"
            $mismatch++
            continue
        }
        $existing = [System.IO.File]::ReadAllText($csPath)
        # 正規化換行後比對
        $normGen = $generated -replace "`r`n", "`n"
        $normExist = $existing -replace "`r`n", "`n"
        if ($normGen -ne $normExist) {
            Write-Host "FAIL $culture .cs 與 JSON 不一致（請跑 eng/Generate-LocalizerExceptionsFromJson.ps1）"
            $mismatch++
        }
        else {
            Write-Host "OK   $culture（$($map.Count) keys）"
        }
    }
    else {
        [System.IO.File]::WriteAllText($csPath, $generated, $utf8Bom)
        Write-Host "WROTE $culture（$($map.Count) keys）"
    }
}

if ($mismatch -gt 0) {
    throw "在地化 JSON／CS 驗證失敗（$mismatch 項）。"
}

$modeText = if ($VerifyOnly) { '且與 .cs 一致' } else { '，已寫入 .cs' }
Write-Host "PASS：12 語系 JSON 鍵對等$modeText（$($baseline.Count) keys）。"
