using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace OdfKit.Tools.OdfSchemaGenerator;

public sealed class DomWrappersCSharpWriter
{
    private static readonly HashSet<string> HandWrittenClasses = new HashSet<string>(StringComparer.Ordinal)
    {
        "TextPElement", "TextHElement", "TextSpanElement", "TextListElement", "TextListItemElement",
        "TextSectionElement", "TextBookmarkElement", "TextNoteElement", "OfficeAnnotationElement",
        "TableTableElement", "TableTableRowElement", "TableTableCellElement", "TableCoveredTableCellElement",
        "TableNamedRangeElement", "TableDatabaseRangeElement",
        "DrawFrameElement", "DrawImageElement", "DrawObjectElement", "DrawShapeElement", "DrawGroupElement", "DrawConnectorElement",
        "StyleStyleElement", "StyleDefaultStyleElement", "StyleMasterPageElement", "StylePageLayoutElement",
        "StyleTextPropertiesElement", "StyleParagraphPropertiesElement",
        "OfficeDocumentElement", "OfficeDocumentContentElement", "OfficeBodyElement", "OfficeTextElement",
        "OfficeSpreadsheetElement", "OfficePresentationElement", "OfficeDrawingElement",
        "ManifestManifestElement", "ManifestFileEntryElement", "ManifestEncryptionDataElement"
    };

    public void Write(SchemaMetadata metadata, TextWriter writer)
    {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using OdfKit.Core;");
        writer.WriteLine("using OdfKit.Compliance;");
        writer.WriteLine();
        writer.WriteLine("namespace OdfKit.DOM");
        writer.WriteLine("{");

        var sortedElements = metadata.Elements
            .OrderBy(e => e.NamespaceUri, StringComparer.Ordinal)
            .ThenBy(e => e.LocalName, StringComparer.Ordinal)
            .ToList();

        // Write wrapper classes
        foreach (var element in sortedElements)
        {
            string nsPrefix = GetNamespacePascalName(element.NamespaceUri);
            string localPascal = ToPascalCase(element.LocalName);
            string className = nsPrefix + localPascal + "Element";

            if (HandWrittenClasses.Contains(className))
            {
                continue; // Skip generating class as it is hand-written in OdfElement.cs
            }

            writer.WriteLine($"    /// <summary>");
            writer.WriteLine($"    /// Typed wrapper for element &lt;{GetPrefix(element.NamespaceUri)}:{element.LocalName}&gt;.");
            writer.WriteLine($"    /// </summary>");
            writer.WriteLine($"    public partial class {className} : OdfElement");
            writer.WriteLine("    {");
            writer.WriteLine($"        public {className}(string? prefix = null) : base(\"{element.LocalName}\", \"{element.NamespaceUri}\", prefix) {{ }}");
            writer.WriteLine("    }");
            writer.WriteLine();
        }

        // Write OdfNodeFactory partial class
        writer.WriteLine("    public static partial class OdfNodeFactory");
        writer.WriteLine("    {");
        writer.WriteLine("        public static OdfNode? CreateGeneratedElement(string localName, string namespaceUri, string? prefix)");
        writer.WriteLine("        {");

        // Group by namespace URI
        var groups = sortedElements.GroupBy(e => e.NamespaceUri).ToList();
        bool firstGroup = true;
        foreach (var group in groups)
        {
            if (firstGroup)
            {
                writer.WriteLine($"            if (namespaceUri == \"{group.Key}\")");
                firstGroup = false;
            }
            else
            {
                writer.WriteLine($"            else if (namespaceUri == \"{group.Key}\")");
            }
            writer.WriteLine("            {");
            writer.WriteLine("                switch (localName)");
            writer.WriteLine("                {");
            foreach (var element in group)
            {
                string nsPrefix = GetNamespacePascalName(element.NamespaceUri);
                string localPascal = ToPascalCase(element.LocalName);
                string className = nsPrefix + localPascal + "Element";
                writer.WriteLine($"                    case \"{element.LocalName}\": return new {className}(prefix);");
            }
            writer.WriteLine("                }");
            writer.WriteLine("            }");
        }

        writer.WriteLine("            return null;");
        writer.WriteLine("        }");
        writer.WriteLine("    }");
        writer.WriteLine("}");
    }

    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return string.Empty;
        var parts = s.Split(new[] { '-', '_', ':', '.' }, StringSplitOptions.RemoveEmptyEntries);
        var pascalParts = parts.Select(p => {
            if (p.Length == 0) return string.Empty;
            return char.ToUpper(p[0]) + p.Substring(1);
        });
        return string.Join("", pascalParts);
    }

    private static string? GetNamespacePrefix(string namespaceUri)
    {
        return namespaceUri switch
        {
            "urn:oasis:names:tc:opendocument:xmlns:office:1.0" => "Office",
            "urn:oasis:names:tc:opendocument:xmlns:style:1.0" => "Style",
            "urn:oasis:names:tc:opendocument:xmlns:text:1.0" => "Text",
            "urn:oasis:names:tc:opendocument:xmlns:table:1.0" => "Table",
            "urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" => "Draw",
            "urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" => "Fo",
            "http://www.w3.org/1999/xlink" => "XLink",
            "http://purl.org/dc/elements/1.1/" => "Dc",
            "urn:oasis:names:tc:opendocument:xmlns:meta:1.0" => "Meta",
            "urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0" => "Number",
            "urn:oasis:names:tc:opendocument:xmlns:presentation:1.0" => "Presentation",
            "urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" => "Svg",
            "urn:oasis:names:tc:opendocument:xmlns:chart:1.0" => "Chart",
            "urn:oasis:names:tc:opendocument:xmlns:config:1.0" => "Config",
            "urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" => "Manifest",
            "urn:oasis:names:tc:opendocument:xmlns:digitalsignature:1.0" => "Dsig",
            "http://www.w3.org/2000/09/xmldsig#" => "Ds",
            _ => null
        };
    }

    private static string GetPrefix(string namespaceUri)
    {
        string? p = GetNamespacePrefix(namespaceUri);
        return p != null ? p.ToLowerInvariant() : "ns";
    }

    private static string GetNamespacePascalName(string namespaceUri)
    {
        string? prefix = GetNamespacePrefix(namespaceUri);
        if (prefix != null) return prefix;

        // Fallback: extract last segment or parse it
        string segment = namespaceUri;
        if (namespaceUri.StartsWith("urn:", StringComparison.Ordinal))
        {
            var parts = namespaceUri.Split(':');
            if (parts.Length > 0)
            {
                segment = parts[parts.Length - 1];
                if (segment == "1.0" || segment == "2.0" || segment == "3.0")
                {
                    if (parts.Length > 1) segment = parts[parts.Length - 2];
                }
            }
        }
        else
        {
            var parts = namespaceUri.Split('/');
            if (parts.Length > 0)
            {
                segment = parts[parts.Length - 1];
                if (string.IsNullOrEmpty(segment) && parts.Length > 1)
                {
                    segment = parts[parts.Length - 2];
                }
            }
        }
        return ToPascalCase(segment);
    }
}
