using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace OdfKit.Tools.OdfSchemaGenerator;

public sealed class DomWrappersCSharpWriter
{
    private static readonly HashSet<string> HandWrittenClasses = new HashSet<string>(StringComparer.Ordinal)
    {
        "TextPElement", "TextHElement", "TextSpanElement", "TextListElement", "TextListItemElement",
        "TextSectionElement", "TextBookmarkElement", "TextNoteElement", "OfficeAnnotationElement",
        "TableTableElement", "TableTableRowElement", "TableTableCellElement", "TableCoveredTableCellElement",
        "TableNamedRangeElement", "TableDatabaseRangeElement",
        "DrawFrameElement", "DrawImageElement", "DrawObjectElement", "DrawShapeElement", "DrawGroupElement", "DrawConnectorElement",
        "StyleStyleElement", "StyleDefaultStyleElement", "StyleMasterPageElement", "StylePageLayoutElement",
        "StyleTextPropertiesElement", "StyleParagraphPropertiesElement",
        "OfficeDocumentElement", "OfficeDocumentContentElement", "OfficeBodyElement", "OfficeTextElement",
        "OfficeSpreadsheetElement", "OfficePresentationElement", "OfficeDrawingElement",
        "ManifestManifestElement", "ManifestFileEntryElement", "ManifestEncryptionDataElement"
    };

    public void Write(SchemaMetadata metadata, TextWriter writer)
    {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("#pragma warning disable 1591 // Suppress CS1591 (missing XML comments) for generated DOM wrappers as they are machine-generated");
        writer.WriteLine("using System;");
        writer.WriteLine("using OdfKit.Core;");
        writer.WriteLine("using OdfKit.Compliance;");
        writer.WriteLine();
        writer.WriteLine("namespace OdfKit.DOM");
        writer.WriteLine("{");

        var elementAttributes = ResolveAllElementAttributes(metadata);

        var sortedElements = metadata.Elements
            .OrderBy(e => e.NamespaceUri, StringComparer.Ordinal)
            .ThenBy(e => e.LocalName, StringComparer.Ordinal)
            .ToList();

        // Write wrapper classes
        foreach (var element in sortedElements)
        {
            string nsPrefix = GetNamespacePascalName(element.NamespaceUri);
            string localPascal = ToPascalCase(element.LocalName);
            string className = nsPrefix + localPascal + "Element";

            if (HandWrittenClasses.Contains(className))
            {
                continue; // Skip generating class as it is hand-written in OdfElement.cs
            }

            writer.WriteLine($"    /// <summary>");
            writer.WriteLine($"    /// Typed wrapper for element &lt;{GetPrefix(element.NamespaceUri)}:{element.LocalName}&gt;.");
            writer.WriteLine($"    /// </summary>");
            writer.WriteLine($"    public partial class {className} : OdfElement");
            writer.WriteLine("    {");
            writer.WriteLine($"        public {className}(string? prefix = null) : base(\"{element.LocalName}\", \"{element.NamespaceUri}\", prefix) {{ }}");

            // Write version-aware property accessors
            if (elementAttributes.TryGetValue((element.NamespaceUri, element.LocalName), out var attrs))
            {
                var resolvedNames = ResolvePropertyNames(attrs);
                foreach (var attr in attrs.OrderBy(a => resolvedNames[a], StringComparer.Ordinal))
                {
                    string propName = resolvedNames[attr];
                    string prefix = GetPrefix(attr.NamespaceUri);
                    WriteAttributeProperty(writer, attr, propName, prefix);
                }
            }

            writer.WriteLine("    }");
            writer.WriteLine();
        }

        // Write OdfNodeFactory partial class
        writer.WriteLine("    public static partial class OdfNodeFactory");
        writer.WriteLine("    {");
        writer.WriteLine("        public static OdfNode? CreateGeneratedElement(string localName, string namespaceUri, string? prefix)");
        writer.WriteLine("        {");

        // Group by namespace URI
        var groups = sortedElements.GroupBy(e => e.NamespaceUri).ToList();
        bool firstGroup = true;
        foreach (var group in groups)
        {
            if (firstGroup)
            {
                writer.WriteLine($"            if (namespaceUri == \"{group.Key}\")");
                firstGroup = false;
            }
            else
            {
                writer.WriteLine($"            else if (namespaceUri == \"{group.Key}\")");
            }
            writer.WriteLine("            {");
            writer.WriteLine("                switch (localName)");
            writer.WriteLine("                {");
            foreach (var element in group)
            {
                string nsPrefix = GetNamespacePascalName(element.NamespaceUri);
                string localPascal = ToPascalCase(element.LocalName);
                string className = nsPrefix + localPascal + "Element";
                writer.WriteLine($"                    case \"{element.LocalName}\": return new {className}(prefix);");
            }
            writer.WriteLine("                }");
            writer.WriteLine("            }");
        }

        writer.WriteLine("            return null;");
        writer.WriteLine("        }");
        writer.WriteLine("    }");
        writer.WriteLine("}");
    }

    private static Dictionary<(string, string), List<AttributePropertyMetadata>> ResolveAllElementAttributes(SchemaMetadata metadata)
    {
        var elementAttributes = new Dictionary<(string, string), List<AttributePropertyMetadata>>();
        var elementNodes = new List<SchemaPatternNodeMetadata>();

        foreach (var pattern in metadata.Patterns)
        {
            foreach (var node in pattern.PatternTree)
            {
                FindElementNodes(node, elementNodes);
            }
        }

        foreach (var node in elementNodes)
        {
            var key = (node.NamespaceUri, node.LocalName);
            if (!elementAttributes.TryGetValue(key, out var attrs))
            {
                attrs = new List<AttributePropertyMetadata>();
                elementAttributes[key] = attrs;
            }

            var collected = new List<AttributePropertyMetadata>();
            CollectAttributes(node, collected, metadata, new HashSet<string>());

            foreach (var attr in collected)
            {
                AttributePropertyMetadata? existing = attrs.FirstOrDefault(a =>
                    a.NamespaceUri == attr.NamespaceUri &&
                    a.LocalName == attr.LocalName);
                if (existing is null)
                {
                    attrs.Add(attr);
                    continue;
                }

                existing.ValueKind = MergeValueKinds(existing.ValueKind, attr.ValueKind);
            }
        }

        return elementAttributes;
    }

    private static void FindElementNodes(SchemaPatternNodeMetadata node, List<SchemaPatternNodeMetadata> elementNodes)
    {
        if (node.Kind == "element")
        {
            elementNodes.Add(node);
        }
        foreach (var child in node.Children)
        {
            FindElementNodes(child, elementNodes);
        }
    }

    private static void CollectAttributes(SchemaPatternNodeMetadata node, List<AttributePropertyMetadata> attrs, SchemaMetadata metadata, HashSet<string> visitedRefs)
    {
        if (node.Kind == "attribute" && !string.IsNullOrEmpty(node.LocalName))
        {
            attrs.Add(new AttributePropertyMetadata
            {
                NamespaceUri = node.NamespaceUri,
                LocalName = node.LocalName,
                ValueKind = InferAttributeValueKind(node, metadata, new HashSet<string>())
            });
        }
        else if (node.Kind == "ref" && !string.IsNullOrEmpty(node.ReferenceName) && visitedRefs.Add(node.ReferenceName))
        {
            var refPattern = metadata.Patterns.FirstOrDefault(p => p.Name == node.ReferenceName);
            if (refPattern != null)
            {
                foreach (var refNode in refPattern.PatternTree)
                {
                    CollectAttributes(refNode, attrs, metadata, visitedRefs);
                }
            }
        }
        foreach (var child in node.Children)
        {
            CollectAttributes(child, attrs, metadata, visitedRefs);
        }
    }

    private static Dictionary<AttributePropertyMetadata, string> ResolvePropertyNames(List<AttributePropertyMetadata> attrs)
    {
        var reservedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "NodeType", "LocalName", "NamespaceUri", "Prefix", "Parent", "Children",
            "Attributes", "TextContent", "CloneNode", "ImportNode", "GetAttribute",
            "SetAttribute", "RemoveAttribute", "AppendChild", "InsertBefore", "InsertAfter",
            "RemoveChild", "GetDocumentVersion", "GetAttributeValue", "SetAttributeValue"
        };

        var usedNames = new HashSet<string>(reservedNames, StringComparer.OrdinalIgnoreCase);
        var propNames = new Dictionary<AttributePropertyMetadata, string>();

        var localNameGroups = attrs.GroupBy(a => ToPascalCase(a.LocalName)).ToList();
        foreach (var group in localNameGroups)
        {
            if (group.Count() == 1)
            {
                var attr = group.First();
                string name = ToPascalCase(attr.LocalName);
                if (usedNames.Add(name))
                {
                    propNames[attr] = name;
                }
                else
                {
                    string altName = GetNamespacePascalName(attr.NamespaceUri) + name;
                    if (usedNames.Add(altName))
                    {
                        propNames[attr] = altName;
                    }
                    else
                    {
                        altName += "Attribute";
                        int counter = 1;
                        while (!usedNames.Add(altName))
                        {
                            altName = GetNamespacePascalName(attr.NamespaceUri) + name + "Attribute" + counter;
                            counter++;
                        }
                        propNames[attr] = altName;
                    }
                }
            }
            else
            {
                foreach (var attr in group)
                {
                    string name = GetNamespacePascalName(attr.NamespaceUri) + ToPascalCase(attr.LocalName);
                    if (usedNames.Add(name))
                    {
                        propNames[attr] = name;
                    }
                    else
                    {
                        name += "Attribute";
                        int counter = 1;
                        while (!usedNames.Add(name))
                        {
                            name = GetNamespacePascalName(attr.NamespaceUri) + ToPascalCase(attr.LocalName) + "Attribute" + counter;
                            counter++;
                        }
                        propNames[attr] = name;
                    }
                }
            }
        }

        return propNames;
    }

    private static AttributeValueKind InferAttributeValueKind(SchemaPatternNodeMetadata node, SchemaMetadata metadata, HashSet<string> visitedRefs)
    {
        if (node.NamespaceUri == "urn:oasis:names:tc:opendocument:xmlns:style:1.0" &&
            node.LocalName == "family")
        {
            return AttributeValueKind.StyleFamily;
        }

        AttributeValueKind valueKind = AttributeValueKind.Unknown;
        foreach (var child in node.Children)
        {
            valueKind = MergeValueKinds(valueKind, InferValueKind(child, metadata, visitedRefs));
        }

        return valueKind == AttributeValueKind.Unknown ? AttributeValueKind.String : valueKind;
    }

    private static AttributeValueKind InferValueKind(SchemaPatternNodeMetadata node, SchemaMetadata metadata, HashSet<string> visitedRefs)
    {
        if (node.Kind == "data" || node.Kind == "value")
        {
            return GetValueKind(node.DataType);
        }

        if ((node.Kind == "ref" || node.Kind == "parentRef") &&
            !string.IsNullOrEmpty(node.ReferenceName) &&
            visitedRefs.Add(node.ReferenceName))
        {
            var refPattern = metadata.Patterns.FirstOrDefault(p => p.Name == node.ReferenceName);
            if (refPattern is not null)
            {
                AttributeValueKind valueKind = AttributeValueKind.Unknown;
                foreach (var refNode in refPattern.PatternTree)
                {
                    valueKind = MergeValueKinds(valueKind, InferValueKind(refNode, metadata, visitedRefs));
                }

                return valueKind;
            }
        }

        AttributeValueKind childValueKind = AttributeValueKind.Unknown;
        foreach (var child in node.Children)
        {
            childValueKind = MergeValueKinds(childValueKind, InferValueKind(child, metadata, visitedRefs));
        }

        return childValueKind;
    }

    private static AttributeValueKind GetValueKind(string dataType)
    {
        string normalized = dataType.Replace("-", string.Empty).ToLowerInvariant();
        return normalized switch
        {
            "boolean" => AttributeValueKind.Boolean,
            "byte" or "short" or "int" or "integer" or "long" or "nonnegativeinteger" or "positiveinteger" or "nonpositiveinteger" or "negativeinteger" => AttributeValueKind.Int32,
            "decimal" or "double" or "float" => AttributeValueKind.Decimal,
            "date" or "datetime" => AttributeValueKind.DateTime,
            "string" or "normalizedstring" or "token" or "language" or "name" or "ncname" or "id" or "idref" or "anyuri" => AttributeValueKind.String,
            _ => AttributeValueKind.String
        };
    }

    private static AttributeValueKind MergeValueKinds(AttributeValueKind first, AttributeValueKind second)
    {
        if (first == AttributeValueKind.Unknown)
        {
            return second;
        }

        if (second == AttributeValueKind.Unknown || first == second)
        {
            return first;
        }

        return AttributeValueKind.String;
    }

    private static void WriteAttributeProperty(TextWriter writer, AttributePropertyMetadata attr, string propName, string prefix)
    {
        writer.WriteLine();
        switch (attr.ValueKind)
        {
            case AttributeValueKind.Int32:
                writer.WriteLine($"        public int? {propName}");
                WriteNullableTypedAttributePropertyBody(
                    writer,
                    attr,
                    prefix,
                    "GetNullableInt32AttributeValue",
                    "SetInt32AttributeValue");
                break;
            case AttributeValueKind.Boolean:
                writer.WriteLine($"        public bool? {propName}");
                WriteNullableTypedAttributePropertyBody(
                    writer,
                    attr,
                    prefix,
                    "GetBooleanAttributeValue",
                    "SetBooleanAttributeValue");
                break;
            case AttributeValueKind.Decimal:
                writer.WriteLine($"        public decimal? {propName}");
                WriteNullableTypedAttributePropertyBody(
                    writer,
                    attr,
                    prefix,
                    "GetDecimalAttributeValue",
                    "SetDecimalAttributeValue");
                break;
            case AttributeValueKind.DateTime:
                writer.WriteLine($"        public DateTime? {propName}");
                WriteNullableTypedAttributePropertyBody(
                    writer,
                    attr,
                    prefix,
                    "GetDateTimeAttributeValue",
                    "SetDateTimeAttributeValue");
                break;
            case AttributeValueKind.StyleFamily:
                writer.WriteLine($"        public OdfStyleFamily? {propName}");
                WriteNullableTypedAttributePropertyBody(
                    writer,
                    attr,
                    prefix,
                    "GetStyleFamilyAttributeValue",
                    "SetStyleFamilyAttributeValue");
                break;
            default:
                writer.WriteLine($"        public string? {propName}");
                writer.WriteLine("        {");
                writer.WriteLine($"            get => GetAttributeValue(\"{attr.LocalName}\", \"{attr.NamespaceUri}\", GetDocumentVersion());");
                writer.WriteLine("            set");
                writer.WriteLine("            {");
                writer.WriteLine("                if (value == null)");
                writer.WriteLine($"                    RemoveAttribute(\"{attr.LocalName}\", \"{attr.NamespaceUri}\");");
                writer.WriteLine("                else");
                writer.WriteLine($"                    SetAttributeValue(\"{attr.LocalName}\", \"{attr.NamespaceUri}\", value, \"{prefix}\", GetDocumentVersion());");
                writer.WriteLine("            }");
                writer.WriteLine("        }");
                break;
        }
    }

    private static void WriteNullableTypedAttributePropertyBody(
        TextWriter writer,
        AttributePropertyMetadata attr,
        string prefix,
        string getterName,
        string setterName)
    {
        writer.WriteLine("        {");
        writer.WriteLine($"            get => {getterName}(\"{attr.LocalName}\", \"{attr.NamespaceUri}\", GetDocumentVersion());");
        writer.WriteLine("            set");
        writer.WriteLine("            {");
        writer.WriteLine("                if (value == null)");
        writer.WriteLine($"                    RemoveAttribute(\"{attr.LocalName}\", \"{attr.NamespaceUri}\");");
        writer.WriteLine("                else");
        writer.WriteLine($"                    {setterName}(\"{attr.LocalName}\", \"{attr.NamespaceUri}\", value.Value, \"{prefix}\", GetDocumentVersion());");
        writer.WriteLine("            }");
        writer.WriteLine("        }");
    }

    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return string.Empty;
        var parts = s.Split(new[] { '-', '_', ':', '.' }, StringSplitOptions.RemoveEmptyEntries);
        var pascalParts = parts.Select(p => {
            if (p.Length == 0) return string.Empty;
            return char.ToUpper(p[0]) + p.Substring(1);
        });
        return string.Join("", pascalParts);
    }

    private static string? GetNamespacePrefix(string namespaceUri)
    {
        return namespaceUri switch
        {
            "urn:oasis:names:tc:opendocument:xmlns:office:1.0" => "Office",
            "urn:oasis:names:tc:opendocument:xmlns:style:1.0" => "Style",
            "urn:oasis:names:tc:opendocument:xmlns:text:1.0" => "Text",
            "urn:oasis:names:tc:opendocument:xmlns:table:1.0" => "Table",
            "urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" => "Draw",
            "urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" => "Fo",
            "http://www.w3.org/1999/xlink" => "XLink",
            "http://purl.org/dc/elements/1.1/" => "Dc",
            "urn:oasis:names:tc:opendocument:xmlns:meta:1.0" => "Meta",
            "urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0" => "Number",
            "urn:oasis:names:tc:opendocument:xmlns:presentation:1.0" => "Presentation",
            "urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" => "Svg",
            "urn:oasis:names:tc:opendocument:xmlns:chart:1.0" => "Chart",
            "urn:oasis:names:tc:opendocument:xmlns:config:1.0" => "Config",
            "urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" => "Manifest",
            "urn:oasis:names:tc:opendocument:xmlns:digitalsignature:1.0" => "Dsig",
            "http://www.w3.org/2000/09/xmldsig#" => "Ds",
            _ => null
        };
    }

    private static string GetPrefix(string namespaceUri)
    {
        string? p = GetNamespacePrefix(namespaceUri);
        return p != null ? p.ToLowerInvariant() : "ns";
    }

    private static string GetNamespacePascalName(string namespaceUri)
    {
        string? prefix = GetNamespacePrefix(namespaceUri);
        if (prefix != null) return prefix;

        string segment = namespaceUri;
        if (namespaceUri.StartsWith("urn:", StringComparison.Ordinal))
        {
            var parts = namespaceUri.Split(':');
            if (parts.Length > 0)
            {
                segment = parts[parts.Length - 1];
                if (segment == "1.0" || segment == "2.0" || segment == "3.0")
                {
                    if (parts.Length > 1) segment = parts[parts.Length - 2];
                }
            }
        }
        else
        {
            var parts = namespaceUri.Split('/');
            if (parts.Length > 0)
            {
                segment = parts[parts.Length - 1];
                if (string.IsNullOrEmpty(segment) && parts.Length > 1)
                {
                    segment = parts[parts.Length - 2];
                }
            }
        }
        return ToPascalCase(segment);
    }

    private enum AttributeValueKind
    {
        Unknown,
        String,
        Int32,
        Boolean,
        Decimal,
        DateTime,
        StyleFamily
    }

    private sealed class AttributePropertyMetadata
    {
        public string NamespaceUri { get; set; } = string.Empty;

        public string LocalName { get; set; } = string.Empty;

        public AttributeValueKind ValueKind { get; set; }
    }
}
