using System;
using System.Globalization;
using System.IO;
using System.Linq;

namespace OdfKit.Tools.OdfSchemaGenerator;

/// <summary>
/// 將結構描述中繼資料寫成確定性的 C# 執行階段種子程式碼。
/// </summary>
public sealed class SchemaMetadataCSharpWriter
{
    /// <summary>
    /// 寫出一個可建立 OdfSchemaSet 的 C# 類別。
    /// </summary>
    public void Write(SchemaMetadata metadata, TextWriter writer, string className = "GeneratedOdfSchemaMetadata")
    {
        Write(metadata, writer, className, includeProviderHook: false);
    }

    /// <summary>
    /// 寫出一個 C# 類別，並附加 OdfKit 執行階段提供者掛鉤。
    /// </summary>
    public void WriteProvider(SchemaMetadata metadata, TextWriter writer, string className = "GeneratedOdfSchemaMetadata")
    {
        Write(metadata, writer, className, includeProviderHook: true);
    }

    private void Write(SchemaMetadata metadata, TextWriter writer, string className, bool includeProviderHook)
    {
        if (metadata == null)
            throw new ArgumentNullException(nameof(metadata));
        if (writer == null)
            throw new ArgumentNullException(nameof(writer));
        if (string.IsNullOrWhiteSpace(className))
            throw new ArgumentException("Class name cannot be empty.", nameof(className));

        string odfVersionEnumName = MapVersionToEnumName(metadata.Version);
        bool isOfficialOdf14 = string.Equals(odfVersionEnumName, "Odf14", StringComparison.Ordinal);
        string elementVersionRange = isOfficialOdf14 ? "OdfVersionRange.AllKnown" : $"OdfVersionRange.Exact(OdfVersion.{odfVersionEnumName})";

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("// Generated from OASIS Open Document Format (ODF) schemas.");
        writer.WriteLine("// Copyright (c) OASIS Open. All rights reserved.");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using OdfKit.Compliance;");
        writer.WriteLine();
        writer.WriteLine("namespace OdfKit.Compliance");
        writer.WriteLine("{");
        writer.Write("    internal static class ");
        writer.WriteLine(className);
        writer.WriteLine("    {");
        writer.WriteLine("        public static OdfSchemaSet Create()");
        writer.WriteLine("        {");
        writer.WriteLine("            return Create(null);");
        writer.WriteLine("        }");
        writer.WriteLine();
        writer.WriteLine("        public static OdfSchemaSet Create(OdfSchemaSet? baseSchema)");
        writer.WriteLine("        {");
        writer.WriteLine("            var elements = new List<OdfElementDefinition>");
        writer.WriteLine("            {");

        foreach (SchemaNameMetadata element in metadata.Elements
            .OrderBy(item => item.NamespaceUri, StringComparer.Ordinal)
            .ThenBy(item => item.LocalName, StringComparer.Ordinal))
        {
            string role = GetElementRole(element);
            string documentKind = GetDocumentKind(element);
            writer.Write("                new OdfElementDefinition(new OdfQualifiedName(");
            WriteStringLiteral(writer, element.NamespaceUri);
            writer.Write(", ");
            WriteStringLiteral(writer, element.LocalName);
            writer.Write("), ");
            writer.Write(role);
            writer.Write(", ");
            writer.Write(elementVersionRange);
            if (!string.Equals(documentKind, "OdfDocumentKind.Unknown", StringComparison.Ordinal))
            {
                writer.Write(", ");
                writer.Write(documentKind);
            }

            writer.WriteLine("),");
        }

        writer.WriteLine("            };");
        writer.WriteLine();
        writer.WriteLine("            var attributes = new List<OdfAttributeDefinition>");
        writer.WriteLine("            {");

        foreach (SchemaNameMetadata attribute in metadata.Attributes
            .OrderBy(item => item.NamespaceUri, StringComparer.Ordinal)
            .ThenBy(item => item.LocalName, StringComparer.Ordinal))
        {
            bool isRequiredOnDocumentRoot = IsRequiredOnDocumentRoot(attribute);
            writer.Write("                new OdfAttributeDefinition(new OdfQualifiedName(");
            WriteStringLiteral(writer, attribute.NamespaceUri);
            writer.Write(", ");
            WriteStringLiteral(writer, attribute.LocalName);
            writer.Write("), \"");
            writer.Write(GetAttributeValueType(attribute));
            writer.Write("\", ");
            writer.Write(elementVersionRange);
            if (isRequiredOnDocumentRoot)
            {
                writer.Write(", isRequiredOnDocumentRoot: true");
            }

            writer.WriteLine("),");
        }

        writer.WriteLine("            };");
        writer.WriteLine();
        writer.WriteLine("            var nameClasses = new List<OdfSchemaNameClass>");
        writer.WriteLine("            {");

        foreach (SchemaNameClassMetadata nameClass in metadata.Patterns
            .SelectMany(pattern => pattern.NameClasses)
            .OrderBy(item => item.Kind, StringComparer.Ordinal)
            .ThenBy(item => item.NamespaceUri, StringComparer.Ordinal)
            .ThenBy(item => item.LocalName, StringComparer.Ordinal)
            .ThenBy(item => item.IsExcept))
        {
            writer.Write("                new OdfSchemaNameClass(");
            writer.Write(GetNameClassKind(nameClass));
            writer.Write(", ");
            WriteStringLiteral(writer, nameClass.NamespaceUri);
            writer.Write(", ");
            WriteStringLiteral(writer, nameClass.LocalName);
            writer.Write(", ");
            writer.Write(nameClass.IsExcept ? "true" : "false");
            writer.WriteLine("),");
        }

        writer.WriteLine("            };");
        writer.WriteLine();
        writer.WriteLine("            var patterns = new List<OdfSchemaPatternDefinition>");
        writer.WriteLine("            {");

        foreach (SchemaPatternMetadata pattern in metadata.Patterns
            .Where(item => item.PatternTree.Count > 0)
            .OrderBy(item => item.Name, StringComparer.Ordinal))
        {
            writer.Write("                new OdfSchemaPatternDefinition(");
            WriteStringLiteral(writer, pattern.Name);
            writer.WriteLine(", new[]");
            writer.WriteLine("                {");
            foreach (SchemaPatternNodeMetadata node in pattern.PatternTree)
            {
                WritePatternNode(writer, node, "                    ");
                writer.WriteLine(",");
            }

            writer.WriteLine("                }),");
        }

        writer.WriteLine("            };");
        writer.WriteLine();
        writer.Write("            var generated = new OdfSchemaSet(OdfVersion.");
        writer.Write(odfVersionEnumName);
        writer.Write(", new Uri(");
        WriteStringLiteral(writer, string.IsNullOrWhiteSpace(metadata.Source) ? "about:blank" : metadata.Source);
        writer.Write("), ");
        WriteStringLiteral(writer, string.IsNullOrWhiteSpace(metadata.SourceDate) ? "generated" : metadata.SourceDate);
        writer.WriteLine(", elements, attributes, nameClasses, patterns);");
        writer.WriteLine("            return baseSchema == null ? generated : baseSchema.MergeWith(generated);");
        writer.WriteLine("        }");
        writer.WriteLine("    }");

        if (includeProviderHook)
        {
            writer.WriteLine();
            writer.WriteLine("    internal static partial class OdfGeneratedSchemaProvider");
            writer.WriteLine("    {");
            writer.Write("        static partial void TryCreate");
            writer.Write(odfVersionEnumName);
            writer.WriteLine("Core(OdfSchemaSet baseSchema, ref OdfSchemaSet? generated)");
            writer.WriteLine("        {");
            writer.Write("            generated = ");
            writer.Write(className);
            writer.WriteLine(".Create(baseSchema);");
            writer.WriteLine("        }");
            writer.WriteLine("    }");
        }

        writer.WriteLine("}");
    }

    private static string MapVersionToEnumName(string version)
    {
        return version switch
        {
            "1.0" => "Odf10",
            "1.1" => "Odf11",
            "1.2" => "Odf12",
            "1.3" => "Odf13",
            "1.4" => "Odf14",
            _ => throw new ArgumentException($"Unsupported ODF version: {version}", nameof(version))
        };
    }

    private static string GetElementRole(SchemaNameMetadata element)
    {
        if (!IsOfficeNamespace(element.NamespaceUri))
        {
            return "OdfSchemaElementRole.Element";
        }

        return element.LocalName switch
        {
            "document" or
            "document-content" or
            "document-styles" or
            "document-meta" or
            "document-settings" => "OdfSchemaElementRole.DocumentRoot",
            "text" or
            "spreadsheet" or
            "presentation" or
            "drawing" or
            "chart" or
            "formula" or
            "image" or
            "database" => "OdfSchemaElementRole.BodyContent",
            _ => "OdfSchemaElementRole.Element"
        };
    }

    private static string GetDocumentKind(SchemaNameMetadata element)
    {
        if (!IsOfficeNamespace(element.NamespaceUri))
        {
            return "OdfDocumentKind.Unknown";
        }

        return element.LocalName switch
        {
            "text" => "OdfDocumentKind.Text",
            "spreadsheet" => "OdfDocumentKind.Spreadsheet",
            "presentation" => "OdfDocumentKind.Presentation",
            "drawing" => "OdfDocumentKind.Graphics",
            "chart" => "OdfDocumentKind.Chart",
            "formula" => "OdfDocumentKind.Formula",
            "image" => "OdfDocumentKind.Image",
            "database" => "OdfDocumentKind.Database",
            _ => "OdfDocumentKind.Unknown"
        };
    }

    private static string GetAttributeValueType(SchemaNameMetadata attribute)
    {
        if (IsOfficeNamespace(attribute.NamespaceUri))
        {
            return attribute.LocalName switch
            {
                "version" => "odf-version",
                "mimetype" => "media-type",
                _ => "string"
            };
        }

        return "string";
    }

    private static bool IsRequiredOnDocumentRoot(SchemaNameMetadata attribute)
    {
        return IsOfficeNamespace(attribute.NamespaceUri) &&
            string.Equals(attribute.LocalName, "version", StringComparison.Ordinal);
    }

    private static bool IsOfficeNamespace(string namespaceUri)
    {
        return string.Equals(namespaceUri, "urn:oasis:names:tc:opendocument:xmlns:office:1.0", StringComparison.Ordinal);
    }

    private static string GetNameClassKind(SchemaNameClassMetadata nameClass)
    {
        return nameClass.Kind switch
        {
            "name" => "OdfSchemaNameClassKind.Name",
            "nsName" => "OdfSchemaNameClassKind.NamespaceName",
            "anyName" => "OdfSchemaNameClassKind.AnyName",
            _ => "OdfSchemaNameClassKind.Name"
        };
    }

    private static string GetPatternNodeKind(SchemaPatternNodeMetadata node)
    {
        return node.Kind switch
        {
            "element" => "OdfSchemaPatternNodeKind.Element",
            "attribute" => "OdfSchemaPatternNodeKind.Attribute",
            "ref" => "OdfSchemaPatternNodeKind.Ref",
            "parentRef" => "OdfSchemaPatternNodeKind.Ref",
            "grammar" => "OdfSchemaPatternNodeKind.Group",
            "div" => "OdfSchemaPatternNodeKind.Group",
            "group" => "OdfSchemaPatternNodeKind.Group",
            "choice" => "OdfSchemaPatternNodeKind.Choice",
            "interleave" => "OdfSchemaPatternNodeKind.Interleave",
            "optional" => "OdfSchemaPatternNodeKind.Optional",
            "zeroOrMore" => "OdfSchemaPatternNodeKind.ZeroOrMore",
            "oneOrMore" => "OdfSchemaPatternNodeKind.OneOrMore",
            "except" => "OdfSchemaPatternNodeKind.Except",
            "text" => "OdfSchemaPatternNodeKind.Text",
            "empty" => "OdfSchemaPatternNodeKind.Empty",
            "notAllowed" => "OdfSchemaPatternNodeKind.NotAllowed",
            "data" => "OdfSchemaPatternNodeKind.Data",
            "value" => "OdfSchemaPatternNodeKind.Value",
            "list" => "OdfSchemaPatternNodeKind.List",
            "mixed" => "OdfSchemaPatternNodeKind.Mixed",
            "name" => "OdfSchemaPatternNodeKind.Name",
            "nsName" => "OdfSchemaPatternNodeKind.NamespaceName",
            "anyName" => "OdfSchemaPatternNodeKind.AnyName",
            _ => "OdfSchemaPatternNodeKind.Other"
        };
    }

    private static void WritePatternNode(TextWriter writer, SchemaPatternNodeMetadata node, string indent)
    {
        writer.Write(indent);
        writer.Write("new OdfSchemaPatternNode(");
        writer.Write(GetPatternNodeKind(node));
        writer.Write(", ");
        WriteStringLiteral(writer, node.Occurrence);
        writer.Write(", ");
        WriteStringLiteral(writer, node.NamespaceUri);
        writer.Write(", ");
        WriteStringLiteral(writer, node.LocalName);
        writer.Write(", ");
        WriteStringLiteral(writer, node.ReferenceName);
        writer.Write(", ");
        WriteStringLiteral(writer, node.DataType);
        writer.Write(", ");
        WriteStringLiteral(writer, node.Value);

        if (node.NameClasses.Count == 0 && node.Children.Count == 0 && node.DataParameters.Count == 0 &&
            string.IsNullOrEmpty(node.DataTypeLibrary))
        {
            writer.Write(")");
            return;
        }

        writer.WriteLine(",");
        if (node.NameClasses.Count == 0)
        {
            writer.Write(indent);
            writer.Write("    Array.Empty<OdfSchemaNameClass>()");
        }
        else
        {
            writer.Write(indent);
            writer.WriteLine("    new[]");
            writer.Write(indent);
            writer.WriteLine("    {");
            foreach (SchemaNameClassMetadata nameClass in node.NameClasses)
            {
                writer.Write(indent);
                writer.Write("        new OdfSchemaNameClass(");
                writer.Write(GetNameClassKind(nameClass));
                writer.Write(", ");
                WriteStringLiteral(writer, nameClass.NamespaceUri);
                writer.Write(", ");
                WriteStringLiteral(writer, nameClass.LocalName);
                writer.Write(", ");
                writer.Write(nameClass.IsExcept ? "true" : "false");
                writer.WriteLine("),");
            }

            writer.Write(indent);
            writer.Write("    }");
        }

        if (node.Children.Count == 0)
        {
            if (node.DataParameters.Count > 0 || !string.IsNullOrEmpty(node.DataTypeLibrary))
            {
                writer.WriteLine(",");
                writer.Write(indent);
                writer.WriteLine("    Array.Empty<OdfSchemaPatternNode>(),");
                if (node.DataParameters.Count > 0)
                {
                    WriteDataParameters(writer, node, indent);
                }
                else
                {
                    writer.Write(indent);
                    writer.Write("    Array.Empty<KeyValuePair<string, string>>()");
                }

                WriteDataTypeLibrary(writer, node, indent);
            }

            writer.Write(")");
            return;
        }

        writer.WriteLine(",");
        writer.Write(indent);
        writer.WriteLine("    new[]");
        writer.Write(indent);
        writer.WriteLine("    {");
        foreach (SchemaPatternNodeMetadata child in node.Children)
        {
            WritePatternNode(writer, child, indent + "        ");
            writer.WriteLine(",");
        }

        writer.Write(indent);
        writer.Write("    }");

        if (node.DataParameters.Count > 0)
        {
            writer.WriteLine(",");
            WriteDataParameters(writer, node, indent);
        }

        WriteDataTypeLibrary(writer, node, indent);

        writer.Write(")");
    }

    private static void WriteDataTypeLibrary(TextWriter writer, SchemaPatternNodeMetadata node, string indent)
    {
        if (string.IsNullOrEmpty(node.DataTypeLibrary))
        {
            return;
        }

        writer.WriteLine(",");
        writer.Write(indent);
        writer.Write("    dataTypeLibrary: ");
        WriteStringLiteral(writer, node.DataTypeLibrary);
    }

    private static void WriteDataParameters(TextWriter writer, SchemaPatternNodeMetadata node, string indent)
    {
        writer.Write(indent);
        writer.WriteLine("    new[]");
        writer.Write(indent);
        writer.WriteLine("    {");
        foreach (SchemaDatatypeParameterMetadata parameter in node.DataParameters)
        {
            writer.Write(indent);
            writer.Write("        new KeyValuePair<string, string>(");
            WriteStringLiteral(writer, parameter.Name);
            writer.Write(", ");
            WriteStringLiteral(writer, parameter.Value);
            writer.WriteLine("),");
        }

        writer.Write(indent);
        writer.Write("    }");
    }

    private static void WriteStringLiteral(TextWriter writer, string value)
    {
        writer.Write('"');
        foreach (char ch in value)
        {
            switch (ch)
            {
                case '\\':
                    writer.Write("\\\\");
                    break;
                case '"':
                    writer.Write("\\\"");
                    break;
                case '\r':
                    writer.Write("\\r");
                    break;
                case '\n':
                    writer.Write("\\n");
                    break;
                case '\t':
                    writer.Write("\\t");
                    break;
                default:
                    if (char.IsControl(ch))
                    {
                        writer.Write("\\u");
                        writer.Write(((int)ch).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        writer.Write(ch);
                    }

                    break;
            }
        }

        writer.Write('"');
    }
}
