using System.Text.Json;
using OdfKit.Compliance;
using OdfKit.Core;

namespace OdfCorpusGenerator;

internal static class Program
{
    private static readonly string[] ScenarioSlugs =
    [
        "minimal",
        "enriched",
        "metadata",
        "strict-profile",
        "extended-profile",
        "block-content",
        "structure-content",
        "media-content",
        "multi-element",
        "roundtrip-rich"
    ];

    public static int Main(string[] args)
    {
        string repoRoot = args.Length > 0
            ? Path.GetFullPath(args[0])
            : FindRepositoryRoot(Directory.GetCurrentDirectory());

        string corpusRoot = Path.Combine(repoRoot, "tests", "fixtures", "corpus");
        string manifestPath = Path.Combine(corpusRoot, "manifest.json");
        string bulkRoot = Path.Combine(corpusRoot, "generated", "bulk");

        Directory.CreateDirectory(bulkRoot);

        CorpusManifestDocument manifest = CorpusManifestDocument.Load(manifestPath);
        List<CorpusFixtureEntry> preserved = manifest.Fixtures
            .Where(fixture => !fixture.Id.StartsWith("bulk-", StringComparison.Ordinal))
            .ToList();

        List<CorpusFixtureEntry> bulkFixtures = [];
        foreach (OdfFormatInfo format in OdfDocumentKindDetector.SupportedFormats)
        {
            foreach (string scenario in ScenarioSlugs)
            {
                bulkFixtures.Add(GenerateFixture(format, scenario, bulkRoot));
            }
        }

        manifest.Fixtures = [.. preserved, .. bulkFixtures.OrderBy(fixture => fixture.Id, StringComparer.Ordinal)];
        manifest.Save(manifestPath);

        Console.WriteLine($"Wrote {bulkFixtures.Count} bulk fixtures and {manifest.Fixtures.Count} total manifest entries.");
        return 0;
    }

    private static CorpusFixtureEntry GenerateFixture(OdfFormatInfo format, string scenario, string bulkRoot)
    {
        string slug = KindSlug(format.Kind);
        string fileName = $"bulk-{slug}-{scenario}{format.Extension}";
        string relativePath = Path.Combine("generated", "bulk", fileName).Replace('\\', '/');
        string outputPath = Path.Combine(bulkRoot, fileName);

        (OdfVersion version, string profileId, string roundTrip) = ResolveScenarioMetadata(format, scenario);
        WriteMinimalDocument(format, version, outputPath);

        return new CorpusFixtureEntry
        {
            Id = $"bulk-{slug}-{scenario}",
            Path = relativePath,
            Source = "generated",
            License = "generated-no-copyright",
            Kind = format.Kind.ToString(),
            Version = FormatVersion(version),
            Profile = profileId,
            Expected = "valid",
            RoundTrip = roundTrip,
            Notes = $"Bulk minimal corpus fixture for {format.Kind} scenario '{scenario}' generated by OdfCorpusGenerator."
        };
    }

    private static (OdfVersion Version, string ProfileId, string RoundTrip) ResolveScenarioMetadata(
        OdfFormatInfo format,
        string scenario)
    {
        string roundTrip = format.IsFlatXml ? "semantic-equivalent" : "preserve-unknown";
        return scenario switch
        {
            "strict-profile" => (OdfVersion.Odf14, "OASIS_ODF_1_4_Strict", roundTrip),
            "extended-profile" => (OdfVersion.Odf14, "OASIS_ODF_1_4_Extended", roundTrip),
            "roundtrip-rich" when format.Kind == OdfDocumentKind.FlatText =>
                (OdfVersion.Odf13, "OASIS_ODF_1_3", roundTrip),
            "multi-element" when format.Kind == OdfDocumentKind.FlatText =>
                (OdfVersion.Odf12, "ISO_IEC_26300", roundTrip),
            "metadata" when format.Kind == OdfDocumentKind.FlatText =>
                (OdfVersion.Odf11, "OASIS_ODF_1_1", roundTrip),
            _ => (OdfVersion.Odf14, "OASIS_ODF_1_4_Extended", roundTrip)
        };
    }

    private static void WriteMinimalDocument(OdfFormatInfo format, OdfVersion version, string outputPath)
    {
        string? directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        if (format.IsFlatXml)
        {
            using FileStream stream = File.Create(outputPath);
            OdfDocumentFactory.WriteFlatXml(stream, format.Kind, version, leaveOpen: false);
            return;
        }

        using (FileStream stream = File.Create(outputPath))
        using (OdfPackage package = OdfDocumentFactory.CreatePackage(stream, format.Kind, version, leaveOpen: true))
        {
            package.Save();
        }
    }

    private static string KindSlug(OdfDocumentKind kind) =>
        kind.ToString().ToLowerInvariant();

    private static string FormatVersion(OdfVersion version) => version switch
    {
        OdfVersion.Odf11 => "1.1",
        OdfVersion.Odf12 => "1.2",
        OdfVersion.Odf13 => "1.3",
        _ => "1.4"
    };

    private static string FindRepositoryRoot(string startDirectory)
    {
        DirectoryInfo? directory = new(startDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "OdfKit.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException("找不到 repository root。");
    }
}

internal sealed class CorpusManifestDocument
{
    private static JsonSerializerOptions JsonOptions => OdfJsonSerializerOptions.Manifest;

    public List<CorpusFixtureEntry> Fixtures { get; set; } = [];

    public static CorpusManifestDocument Load(string path)
    {
        using FileStream stream = File.OpenRead(path);
        return JsonSerializer.Deserialize<CorpusManifestDocument>(stream, JsonOptions)
            ?? throw new InvalidOperationException($"無法解析 manifest：{path}");
    }

    public void Save(string path)
    {
        using FileStream stream = File.Create(path);
        JsonSerializer.Serialize(stream, this, JsonOptions);
    }
}

internal sealed class CorpusFixtureEntry
{
    public string Id { get; set; } = string.Empty;

    public string Path { get; set; } = string.Empty;

    public string Source { get; set; } = string.Empty;

    public string License { get; set; } = string.Empty;

    public string Kind { get; set; } = string.Empty;

    public string Version { get; set; } = string.Empty;

    public string Profile { get; set; } = string.Empty;

    public string Expected { get; set; } = string.Empty;

    public string RoundTrip { get; set; } = string.Empty;

    public string? Notes { get; set; }
}